### ISSUE TITLE
개인 노트북 사용제한 문제

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [DSM-HS/student-council#1]
개인 노트북을 제한하는 규정은 학교 특성과 전혀 어울리지 않는 것 같습니다.  
그 이유는 다음과 같습니다.

1. CPU
    - 학교 노트북의 CPU가 현재 개인 노트북의 CPU 성능을 따라오지 못함
2. 그래픽 카드
    - GPU를 활용하는 병렬 처리 프로그래밍(CUDA)이 어려움
    - Unity 등 게임 및 3D 엔진 개발이 어려움
3. Mac
    - iOS 개발과 같이 macOS가 필요한 경우, 학교 노트북으로는 불가능함
4. 해상도
    - 1기, 3기 학교 노트북의 경우, 해상도가 1366 x 768이기 때문에 작은 해상도로 불편함이 큼

#### 제안 사항
- [x] 개인 노트북 허가

**Comment by kyle-seongwoo-jun** [comment]
현재 선생님들간의 회의로 다시 결정될 예정이며 결정 전까지 개인 노트북을 사용해도 됩니다.

회의 결과가 나오는 대로 다시 알려드리겠습니다.

**Comment by kyle-seongwoo-jun** [comment]
#  들어가기 앞서
본 글은 회의를 통하여 정해진 개인 노트북 허가에 관한 사항을 정리한 글이다.  
이는 변경될 수 있고 추가 의견을 제시할 경우, 보충될 수 있다.

## 허가의 의의
학생들이 학교 노트북으로 **실습이 불가능한 분야를 개발**할 수 있도록 한다.

## 현재까지의 규제 이유
* 교육 정보부의 제재
* 라이센스 위반 및 불법 소프트웨어 설치 문제

# 본문
## 허가
다음은 개인 노트북 허가에 관한 내용을 서술한다.

### 허가 절차
다음은 개인 노트북 허가 절차에 대한 방법이다.

1. 개인 노트북에 대한 사용 목적 및 이유를 정확히 명시한다.
2. 동아리 지도 교사 등 노트북 사용에 관한 담당 교사의 추천을 받는다.
3. 라이센스 위반시 위반에 대한 벌금을 청구 받는다는 서약서를 작성한다.
4. 허가에 대한 정당성 검토후 허가시 사용 허가 인증 수단을 노트북에 부착한다.

### 개인 노트북 사용 목적의 최소 조건
개인 노트북을 사용하기 위해서는 그에 합당한 목적과 이유가 필요하다.  
사용 목적의 최소 조건은 다음과 같다.
 
* 학교 노트북으로 실습이 불가능한 분야를 개발하는 경우
* 교사가 합당한 목적으로 인정하는 경우

## 사용시 제약 사항
다음은 개인 노트북 사용 시, 제약 사항에 대하여 서술한다.

### 인증 수단
개인 노트북 허가를 받은 경우 반드시 개인 노트북에 인증 수단(스티커)를 부착해야 한다.

### 네트워크

* 개인 노트북의 학교 무선망 사용을 절대적으로 제한한다
* 학교 노트북의 로컬 망을 통한 네트워크 사용도 원칙적으로는 불허하나 자신의 학교 노트북을 사용하는 경우, 이에 대해 제제하지는 않는다.
* 반드시 **자신의 학교 노트북**의 망을 이용해야 해야 하며 **타인의 망 사용은 절대 불허가**한다.
* 사설망 _(ex. 테더링, 핫스팟, 에그)_ 사용은 허가한다.

## 시행 일자
본 규정은 2017년 4월 17일 월요일에 공지되며 4월 18일 화요일부터 시행된다.

## 서약서
![01 -1](https://cloud.githubusercontent.com/assets/16515307/25064064/7e1f41a2-222d-11e7-8fd6-7e67aae5f867.png)

# 마지막으로
## 회의 일자
* 2017년 4월 6일 목요일
* 2017년 4월 12일 수요일
* 2017년 4월 14일 금요일

## 회의 참석자
* 전문교육부장 전호연 선생님
* 교육정보부장 양은정 선생님
* 학생회장 전성우
* 기숙사 자치부장 정원정

**Comment by 98ff98** [comment]
개인 노트북을 사용해야하는 이유에 학교노트북의 괴상한 해상도를 추가해주세요(1366 x 768)

**Comment by kyle-seongwoo-jun** [comment]
@scala-in 추가했습니다 😃

**Comment by jiheon-dev** [comment]
지금 정해진 규칙같은 경우, 언제부터 적용되는 건가요?

**Comment by CRJW** [comment]
한 담당 교사에게 추천을 받아 노트북이 허가되면 학교와 기숙사 양측에서 모두 사용이 가능한 것입니까?
아니면 사감부에서 별개로 허가를 받아야 합니까?
그리고 본 규칙이 적용되는 기간이 더 있다면 그 기간 동안은 개인 노트북이 사용 가능합니까?

**Comment by kyle-seongwoo-jun** [comment]
@smakerdev @CRJW 현재 위 규정은 다음주부터 시행될 예정이며, 기숙사에서의 사용은 아직 사감부와 토의되지 않았습니다. 추후에 다시 말씀드리겠습니다.

**Comment by kyle-seongwoo-jun** [comment]
@CRJW 기숙사에서는 사용이 허가된 시간과 장소에서 사용하시면 됩니다.

**Comment by kyle-seongwoo-jun** [comment]
저번주부터 개인 노트북 신청을 받고 있으며 이번주부터 인증 스티커를 부착하며 시행됩니다.
