### ISSUE TITLE
기숙사 벌점 상쇄 관련

### ISSUE THREAD

**Issue by rscarrera27** [DSM-HS/student-council#10]
# 기숙사 벌점의 적용 기간
 알다시피 기숙사 벌점이 현재 상쇄가 되지 않습니다.
문제는 이 벌점의 유지가 1년 단위라는겁니다. 이는 학생들이 벌점을 유지하기에 매우 힘듭니다. 벌점이 상점으로 상쇄가 되지 않는다면 1년이 아닌 학기단위로 벌점을 적용시켜야 한다고 생각합니다.

**Comment by kyle-seongwoo-jun** [comment]
#7 과 관련된 내용인 것 같습니다. #7 에 코멘트로 달아주세요.
