### ISSUE TITLE
학교 축제 관련

### ISSUE THREAD

**Issue by YuHero** [DSM-HS/student-council#11]
안녕하세요 대덕마이스터고에 재학중인 3학년 학생입니다 다름이 아니라 학교축제관련해서 건의사항이 있어서 안건을 내보려고 합니다 일단 저희학교 3학년들은 2학기에 취업을 나가고 기숙사마저 퇴사하게 됩니다 실질적으로 저희 3학년 들이 학교에 있을수 있는 시간은 1학기 뿐이죠 학교 축제는 보통 2학기에 진행이됩니다만 그 축제에는 3학년이 참여할 수 없게 됩니다. 고등학생 마지막축제가 2학년이 끝이라면 3학년들은 억울하지않겠습니까? 학교 축제를 2학기에서 1학기로 옮겨보는 시스템을 건의합니다. 날짜는 기말고사를 끝으로 여름방학전에 실시하는것을 건의합니다. 부디 건의사항을 잘 검토해주시고 결정해 주시길바랍니다.

#### 제안 사항
- [x] ~~학교 축제 1학기 시행~~ _(학사 일정 수정이 어려움, 소규모 행사로 대체)_

#### 추가 의견
- [x] ~~체육대회 1학기 시행~~ _(학교 운동장 공사로 불가)_

**Comment by jaemin-im** [comment]
저 역시 찬성하는 바입니다. 1학년, 2학년, 그리고 3학년 모두가 참여해야 전교생이 함께 즐겁게 보내는 참된 축제가 되는데, 2학기에 취업을 하게 되는 3학년들이 없게 되어 허전하게 됩니다.

**Comment by SpiralMoon** [comment]
체육대회도 추가로 제안하고 싶습니다.

**Comment by kyle-seongwoo-jun** [comment]
@SpiralMoon 이번주부터 학교 운동장 공사가 시작되어 공사가 최소 9월 중으로 마무리된다고 합니다. 아쉽지만 체육대회는 1학기 중으로 진행하기 어려울 것 같습니다.

**Comment by kyle-seongwoo-jun** [comment]
@YuHero @Xsolute 학교 축제의 경우, 11월 17일로 확정되었습니다. [학사 일정](http://dsmhs.djsch.kr/scheduleH/list.do?section=2)을 수정하기는 어려울 것 같습니다. 대신 '쇼 머더 대마'와 같은 크고 작은 행사가 열릴 예정이 있으니 많은 참여와 관심 부탁드립니다.
