### ISSUE TITLE
아침 조회 전 노트북 사용

### ISSUE THREAD

**Issue by ghost** [DSM-HS/student-council#12]
## 현황
 아침 조회 전에 노트북 사용이 금지되어 있습니다(2학년).

## 요구
- [x] ~~아침 조회 전에 노트북을 사용할 수 있도록 해 주십시오.~~ __(문서 출력으로 해결)__

## 이유
 * HTML, PDF 등의 형식의 전자 문서를 읽을 수 없어서 공부 효율이 떨어집니다.
 * 학교 특성상, 개인적인 공부를 할 수 있는 시간이 숙제를 하는 데에 드는 시간을 포함하여 몇 시간밖에 없습니다. 단 30분도 이 시간에 대하여 꽤 큰 비를 차지합니다.
 * 책으로 배우지 못하는 것이 존재합니다.<sup>[예](https://github.com/wlzla000/My_external_stars/blob/master/Security.md)</sup>

**Comment by seunghun-kim** [comment]
1층에 프린터가 있는데, 전자 문서는 필요한 걸 미리 인쇄해 두었다가 보는 건 어떤가요?

**Comment by ghost** [comment]
@dwcy2306 좋은 생각이네요.
A4 용지 한 박스랑 스테이플러 하나 사야겠어요.

**Comment by ghost** [comment]
직접 인쇄해 보니 한 문서<sub>article</sub>에 A4 용지 30장 정도 나오네요. 간혹 글자와 그림이 잘린다는 점만 빼면 나쁘지 않아요.

**Comment by kyle-seongwoo-jun** [comment]
@wlzla000 해결되신 건가요?

**Comment by ghost** [comment]
일단 _제가 필요로 한 부분_ 은 해결된 것 같네요.
다른 사람이 또 다른 근거를 가져와 이 이슈를 다시 열고자 할 때에 다시 여는 것으로 합시다.
