### ISSUE TITLE
기숙사 시설 개선 및 추가 사항

### ISSUE THREAD

**Issue by SeungYongSon** [DSM-HS/student-council#13]
**더욱 나은 기숙사**를 만들기 위해 기숙사 내에서 **불편한 점**과 **개선했으면 하는점**, **추가됬으면 하는것들**을 여기다 적어졌으면 합니다.  

많은 학생 여러분의 아이디어와 참여 부탁드립니다.  :D 

#### 추가 의견
- [ ] 호실 내 노트북 사용이 금지된 이유 확인 원함
- [x] ~~샤워실 수압 및 최고 온도 상승~~ (일부 호실의 문제)
- [x] 여학생 여성용품 쓰레기통 크기 확장
- [ ] 아침 달리기 폐지
- [x] ~~호실 책장 설치~~ (예산 상의 어려움)
- [x] ~~호실 내 테이블(사이드 테이블, 베드 테이블) 설치~~ (자습실에서 공부 지향)
- [x] ~~DMS 시스템 잔류조사 디폴트값 변경~~ (학생회 해결 문제가 아님)
- [x] ~~라온실의 개인 자습공간 조성~~ (개인 자습실을 다온실로 변경)
- [x] ~~11시 이후 전기 사용~~ (기각)

**Comment by Kinter** [comment]
기숙사 방안에서의 노트북 사용이 금지된 이유에 대해서 알고 싶습니다.

내용 추가 +) 호실내에서는 무선망 사용이 안되서 온라인 게임은 사실상 힘들다고 볼 수 있음.

**Comment by SammyOut** [comment]
샤워실 수압이랑 최고온도가 높혀졌으면 좋겠습니다.

**Comment by ghost** [comment]
여학생 여성용품 쓰레기통 크기 좀 키워주십시오..

**Comment by KimEJ** [comment]
아침달리기 폐지좀 해 주세요...

**Comment by ghost** [comment]
호실에 책장을 설치해주세요.

**Comment by ghost** [comment]
호실에서 공부하는 학생의 수가 적지 않은데, 공부하기에 환경이 너무 부적절 합니다. 사이드 테이블이나 베드테이블 등이 구비되었으면 합니다.

**Comment by KimEJ** [comment]
dms 잔류조사 디폴트값 변경 가능하게 만들어주세요

**Comment by kyle-seongwoo-jun** [comment]
@KimEJ 그 부분은 저희 해결 사항이 아닌 것 같습니다. [DMS 개발 페이지](https://github.com/rlatjdfo112/DSM-Dormitory-System)에 문의해주시길 바랍니다.

**Comment by ghost** [comment]
라온실이 개인 자습공간으로 지정되었는데, 개인적인 공부를 하기에 적합한 환경이 아닙니다.
따라서 다음과 같은 안을 제안하고자 합니다.

1. 독서실과 같이 칸막이 설치 및 좌석 배치(좌석이 토론 등 대화를 하기에 적합한 배치임. 따라서 소란스러워 지기 쉬우며, 집중력이 흐트러짐)
![사진 참조바람](https://cloud.githubusercontent.com/assets/24401760/25555288/58c0c106-2d1d-11e7-8413-486cb00a6ce7.png)

2. 복도쪽 유리(?)를 불투명 하게 개선 (복도쪽 유리가 투명함에 따라, 집중력에 방해가 됨)
3. 소란행위를 하는 학생에게 벌점 등 제제(소란행위는 다른 학생의 학습에 방해가 될 수 있음)
4. 펜던트 조명 설치 및 좌석별 스탠드 설치
위 에서 제시한 스탠드와 유사하면 좋을 것 같음

**Comment by ghost** [comment]
여름이 되면 저녁에 모기나 곤충들이 많습니다. 작년에는
 저녁 11시 이후에 전기가 들어와서 홈키퍼 등을 사용하였는데 올해는 기숙사 내에 전기가 끊겨서 벌레들이 들어오면 막을 수가 없습니다. 저녁 11시 이후에 전기를 들어오게 해주세요

**Comment by kyle-seongwoo-jun** [comment]
@IRSM 일부 호실의 문제인 것 같습니다. 사감선생님께 말씀드려 타호실에 비해 수압과 수온이 낮은 경우, 수리를 받아 해결하시면 됩니다.

**Comment by kyle-seongwoo-jun** [comment]
@KiCH99 회의 결과, 크기 확장이 아닌 하나 더 추가 배치하는 것으로 결정되었습니다.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 라온실의 자리 배치를 말씀하신대로 독서실과 비슷하게 다온실과 같이 바꾸고 스탠드도 설치할 수 있도록 결정했으나 아직 확정은 아닙니다. 복도쪽 유리를 불투명하는 것은 사감선생님의 순찰이 어려워지는 등의 이유로 어려울 것 같습니다.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 호실 내 책장 설치나 사이드 테이블, 베드 테이블 설치는 어려울 것 같네요. 호실 내 공부하는 학생들이 적지는 않지만 학교에서는 기숙사 자습실에서 공부를 하는 것을 지향하고 있으며 예산 상의 문제가 가장 큽니다. 

원하시는 경우, 직접 설치하여 사용하시면 됩니다.

**Comment by kyle-seongwoo-jun** [comment]
@dogyhbin2 벌레에 대해서는 현재 대안책을 준비 중입니다. 이로 인한 11시 이후에 전기 사용 허가는 어려울 것 같습니다.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 개인 자습실을 말씀하신대로 독서실과 자리 배치가 비슷한 다온실로 변경하였습니다. [참고](https://www.facebook.com/dsmfriendship/posts/1394578083942619)

**Comment by kyle-seongwoo-jun** [comment]
@KiCH99 여성 쓰레기통을 추가로 하나 배치하였습니다. [참고](https://www.facebook.com/dsmfriendship/posts/1394578083942619)
