### ISSUE TITLE
[공약] 학생 연합 관련 의견

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [DSM-HS/student-council#14]
학생 연합 조직에 대한 학생 여러분의 의견을 수렴하고자 합니다.

자유롭게 여러분들의 의견을 제시해주시길 바랍니다.

ex) _학생 연합 안 만들어도 좋을 것 같아요._

**Comment by ghost** [comment]
학생 연합은 본교 학생의 이해와 요구에 따라 학생의 복지증진,  불편한 점 해결, 좋은 학습환경 제공 및 휴식 을 제공하는데에 그 목적성을 두며, 학생들이 직접 참여할 수 있는 현 자치회처럼 간접적인 참여가 아닌, 직접적인 참여를 지향했으면 좋겠습니다.
