### ISSUE TITLE
[공약] 피트니스 센터 시설 추가 관련

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [DSM-HS/student-council#15]
저희 공약 중에 피트니스 센터에 음향시설과 연예인 브로마이드를 추가하는 것이 있었습니다. 
이 안건에 대해 학생 여러분의 안건을 수령하고자 합니다. 
자유롭게 여러분들의 의견을 제시해주세요.

**Comment by AshtonYoon** [comment]
스피커 설치는 좋은 것 같습니다 :) 만약 설치하게 된다면 노트북에 페어링해서 사용해야할까요?

**Comment by graykick** [comment]
스피커를 설치하게 될경우,  그 스피커의 주도권(?)에 대한 문제가 발생할것 같습니다. (피트니스 센터당 스피커가 1set 일경우) 
대부분 음악을 재생하는데 사용될것 같은데, 개인의 취향은 모두 다르기때문입니다. 
2년전 기상음악을 신청하는것 같이, 신청곡을 받는 형태가 되어야할것 같습니다.

**Comment by ghost** [comment]
유튜브 라이브등의 방송프로그램을 비공개로 연 후, 신청받는 라디오의 형태나 ([예시](https://www.youtube.com/watch?v=e-zbKcCC0R)) 아니면 신청식 라디오 프로그램을 제작(기상음악 신청도 할 수 있으면 좋을 것 같음) 하는건 어떨까요?
