### ISSUE TITLE
[제안] 호실에서의 스탠드 사용

### ISSUE THREAD

**Issue by ghost** [DSM-HS/student-council#17]
# 제안 : **호실에서의 스탠드 사용 허가**
---

## 근거

1. 11시 이후에 전기가 끊어짐에 따라, 스탠드 사용은 11시 까지로 제한되므로 8:30 ~ 11:00 까지의 **2시간 정도의 스탠드 사용은 안전 상 문제가 될 여지가 적음** (2시간의 사용으로 화재가 발생할 가능성이 있는 스탠드의 수는 매우 적음)
     1-1. 만약에 2시간 정도의 사용이 안전에 위험이 된다고 판단되면, KC인증 등의 신뢰할 수 있는 **안전
    인증이나 LED등의 안전한 광원을 사용하는 허가가 된 스탠드에 한해서, 스탠드 사용 허가를 할 수도 있
    음** (인증여부 확인이 힘들다면 인증스티커나 도장등으로 확인)

2. **호실에서 공부하는 학생의 수가 적지 않음**

3. 스탠드가 공부 몰입도나 **효율을 높여준다는 주장이 주기적으로 제기**됨

4. 현재 공용실에서 스탠드를 사용하는 방식에 제기될 가능성이 있는 **타인에대한 피해우려가 줄어듬**

#### 제안 사항
- [ ] 호실 내 스탠드 사용

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 8시 30분부터 11시까지 호실에서 불을 끄고 스탠드를 사용하여 공부를 하신다는 말씀이신가요?

**Comment by ghost** [comment]
@Nuwanda22 그 어떤 이유에서도 그런 사항은 강제화 해서는 안됩니다.
호실 학생등의 자율에 맞겨야 할 문제라고 생각됩니다.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 아뇨, 스탠드의 사용 목적을 묻는 것입니다. 8시 30분부터 11시까지는 호실 내 점등이 가능한데 스탠드를 굳이 사용한다는 이유가 불을 끄고 스탠드를 켜는 것이 공부의 효율을 돕기 때문이라는 것 아닌가요?

**Comment by ghost** [comment]
@Nuwanda22  맞습니다. 그러나 스탠드는 불을 켠 상황에서도 더 많은 광원을 특정지역에 집중적으로 주사하여 몰입도를 높입니다.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ [자치회](https://www.facebook.com/dsmfriendship/posts/1340937919306636)에서 처리되었습니다. 원하시는 문제 해결되셨나요?

**Comment by ghost** [comment]
@Nuwanda22 제가 제안한 안건과 약간의 비동일성이 있다고 생각합니다.
> 3. 사감실에 개인 스탠드를 맡겨놓고 자습 시 사용할 수 있도록 함
>     -  자습실의 파티션(칸막이)으로 인해 빛이 차단되어 
 >       스탠드를 이용하는 것이 공부에 효과적이라는 의견

이 문구로 미루어 짐작하건데, 자치회에서 결정된 사안은 공용실로 제한된다 라는 판단이 듭니다.
