### ISSUE TITLE
아침운동 관련 건의

### ISSUE THREAD

**Issue by rscarrera27** [DSM-HS/student-council#18]
현재 주말을 제외한 나머지 요일에는 아침운동을 합니다. 많은 사람들이 아침운동을 힘들어 합니다... 아침운동을 열심히 참여한다고 해서 돌아오는것도 없고 언제 끝나나 짜증만 날 뿐이고 하루하루 버티기 일쑤입니다. 따라서 한달에 한번 __ 아침운동 없는날__을 건의합니다. 만약 이런 날이 있다면 이런 날을 기다리면서라도 아침운동에 좀더 희망적으로 참여할수 있을 것이라고 생각합니다.

**Comment by kyle-seongwoo-jun** [comment]
좋은 의견인 것 같습니다만 주제가 중복되는 것 같네요. #3 에 다시 작성해주시면 감사하겠습니다.
