### ISSUE TITLE
·

### ISSUE THREAD

**Issue by ghost** [DSM-HS/student-council#2]
Boom.

**Comment by wlzla000** [comment]
상기한 대부분의 요소는 기숙사에서 이루어지는 것입니다. 기숙사는 학교를 가기 위하여 잠을 자는 곳입니다. 규제는 타인에게 피해를 입히는 것에 대하여만 적용되어야 이치에 맞습니다.

**Comment by wlzla000** [comment]
그 이외의 행동 제한 및 강제는 시간을 자유롭게 쓰지 못하게 하여 효율을 떨어뜨립니다.

**Comment by wlzla000** [comment]
행동 제한 및 강제는 자기 주도 학습 능력과 그 의욕을 떨어뜨립니다.

 학업에 소홀하는 학생이 행동 제한 및 강제에 의하여 학업에 더 집중한다는 말은 논리적인 비약이 있다고 봅니다.

 주말의 경우에는 잔류자와 비잔류자 간의 차별이 발생하게 됩니다.

**Comment by wlzla000** [comment]
요구되는 학업량이 비교적 많은 마이스터 고등학교의 특성상 취침 시각 제한은 비현실적이라고 봅니다. 학습 시간과 그에 따른 피로 간의 비율 조절은 학생 개인이 자신의 체력을 고려하여 직접 판단하여야 할 사항이라고 생각합니다. 이를 제한하는 일은 학업을 시간 대비 비효율적이게 만들 수 있습니다.

**Comment by wlzla000** [comment]
솔직히 말하면 왜 기숙사를 비롯한 학교 전체를 지옥으로 못 만들어서 안달인지 모르겠습니다. 저는 개인적으로 누구보다 학업에 충실하려고 노력한다고 생각하는데, 배우지도 쉬지도 못하게 하는 각종 기괴한 규제들이 늘어갈 때마다 하루하루가 편하지 않습니다. 정말 괴롭습니다.

 하루에 남는 시간을 모조리 모은 서너 시간의 시간은 망할 숙제를 하는 데에 다 나가고 밤에 책을 읽으려고 하면 불빛이 없어서 못합니다. 정말 배우고 싶어도 배울 수 없어서 불빛이 새지 않도록 옷장을 열어 두고 커튼을 쳐 둔 채 이불을 덮어 쓰거나 화장실에 앉아서 책을 읽었습니다.

 그 짓을 수십 번 하다 보면 이게 대체 무슨 미친 짓인지, 내가 이러려고 배울 학 자 붙어 있는 학교를 다니는 건지, 온갖 생각이 다 납니다.

 제발 부탁드립니다. 규제를 풀고 학생들을 믿어 주세요.

**Comment by wlzla000** [comment]
**가장 편한 곳이 가장 배우기 좋은 곳입니다.**

**Comment by kyle-seongwoo-jun** [comment]
### 안건 제시 목록
#### 기숙사
- [x] 전기 사용 제한
- [ ] 노트북 사용 제한
- [ ] 휴대 전화 사용 제한
- [ ] 조명 사용 제한
- [ ] 취침 시간 제한
- [ ] 아침 운동

#### 학교
- [ ] 강제 자습 해제

### 안건 제시 근거
* 규제는 타인에게 피해를 입히는 것에 대하여만 적용되어야 이치에 맞음
* 행동 제한 및 강제는 시간을 자유롭게 쓰지 못하게 하여 효율을 떨어뜨림
* 학업에 소홀하는 학생이 행동 제한 및 강제에 의하여 학업에 더 집중한다는 말은 논리적인 비약이 있음
* 요구되는 학업량이 비교적 많은 마이스터 고등학교의 특성상 취침 시각 제한은 비현실적임
