### ISSUE TITLE
[질문] 세미나 참여 시, 주말 외출 시간 연장

### ISSUE THREAD

**Issue by jiheon-dev** [DSM-HS/student-council#20]
이번에 스프링 캠프 세미나 외출 관련되서 많은 갈등들이 있었다라는 것을 아는 분은 잘 아실 겁니다.

처음부터 말씀을 드리자면, 저희가 공지를 들은 것은 작년에 세미나, 컨퍼런스 외출 시 본교 전공선생님의 허락 하에 외출 시간 연장이 가능하다라는 것 뿐이었습니다. 하지만, 이번 사건같은 경우에는 저희 동아리 'WCE'와 '시나브로' 같은 경우는 소프트웨어 개발과 부장 선생님의 허락을 받았음에도 불구하고, 외출 시간 연장이 **불가능**하였습니다. 

이런 문제에 대해서 말씀을 드리고자 깃허브에 이슈를 남깁니다.

사감부장 선생님께서 처음에 말씀하시길, "작년부터 8:30분 귀사가 원래 규정이고, 집이 먼 학생들 때문에 외출 시간 연장에 대해서 배려를 해주었다. 하지만, 이번 년도부터 변경되었다."라고 말씀을 하셨었는데,

이번 년도 3월말에 있던 세미나를 이유로 12시 이후에 들어온 학생들은 물론, 저희는 작년 규정이 바뀌었는지도 모르고 있었습니다. 그 규정이 바뀐 이후에 학생들은 물론, 선생님들께도 공지가 되어 있지 않은 상태였고, 사감부장선생님과 다른 선생님, 즉, 저희 동아리의 외출 시간 연장을 허락해주신 개발과 부장선생님도 물론, 선생님들마다 이야기가 다른 상태입니다. 

지금 이런 상태로 인하여, 세미나에 간 학생들이 토요귀가로 처리를 하여, 기숙사로 행사가 끝난 이후 귀가하지 못하고, 집을 가거나 집이 먼 학생들은 잘 곳을 구해야 했던 일이 있었습니다.

#사감부장선생님의 의견 정리

1. 대회가 늦게 끝나서 대회 외출 시간 연장은 허락이 된다
2. 세미나 외출을 하기 위해서는 주말 현장체험을 쓰고 가야 한다.
3. 세미나에서 발표나 중요한 역할, 즉, 스텝이나 세미나를 주최하는 경우,  주말 외출 시간 연장이 허가된다

입니다.

사감부장 선생님께서 다른 학생에게 세미나를 영화관에 비유하여 "너네들이 원해서 가는 것인데, 중간에 나오면 되지 않으냐"라고 말씀을 하셨습니다. 이 말에 대해서도 이해가 전혀 되지 않습니다.

또한, 저는 물론 다른 학생들도 똑같이 1, 2, 3번 사항에 관하여 들어본 적이 한번도 없습니다.

저희 학교는 왜 항상 선생님들마다 하시는 말씀이 다를까요...?

세미나 주말 외출 시간 연장에 대한 정확한 규정과 이 문제에 대한 확실한 답변 부탁드립니다.

**Comment by kyle-seongwoo-jun** [comment]
다음이 공지된 기숙사 귀사 규정입니다.

## 일반 참가자 
* 평일 및 주말 모두 20:30 귀사 완료
* 지연 귀사가 될 경우 주말-외박 신청, 평일-현장체험학습 연장

## 직접 활동자 
* 대회, 공식초정, 발표 등의 활동자
* 공문 시간 고려 귀사시간 협의 후 연장 가능

**Comment by kyle-seongwoo-jun** [comment]
@smakerdev 답변되셨나요?

**Comment by jiheon-dev** [comment]
@Nuwanda22 제가 요즘 바빠서 확인을 못했네요. 정확한 답변 감사합니다.
지금 사건이 일어난 것이 선생님들 회의를 하고 나서 학생들은 전달받은 것이 없었기 때문에 오해의 소지가 있었던 것 같습니다. 학생들에게 전달될 수 있도록 정확한 공지 부탁드립니다.

**Comment by kyle-seongwoo-jun** [comment]
@smakerdev 기숙사 시스템 페이지 공지사항에 공지를 요청했습니다. 😄
