### ISSUE TITLE
[제안] 건강체력실 탁구채 추가 비치 요청건

### ISSUE THREAD

**Issue by jychoi415** [DSM-HS/student-council#21]
학생들이 점심, 저녁 시간에 급식을 먹고 나서 창의관 1층 건강체력실에서 탁구를 치는 경우가 많습니다. 그런데 펜홀더 타입 탁구채에 비해 쉐이크핸드 타입이 많이 부족하고, 있더라도 멀쩡한 쉐이크핸드 채가 거의 없습니다. 쉐이크핸드 탁구채를 추가적으로 비치하는 것을 요청합니다.

#### 제안 사항
- [ ] 건강체력실 쉐이크핸트 탁구채 추가 비치

**Comment by SongKJ00** [comment]
검토하겠습니다.
