### ISSUE TITLE
연장학습 자리문제(+ 콘센트 수 문제)

### ISSUE THREAD

**Issue by graykick** [DSM-HS/student-council#22]
최근들어 3개 학년이 같이 연장학습을 하게되면서, 기숙사의 학습실 자리가 굉장히 부족하다고 느낍니다.
특히나, 콘센트가 있는 자리에 앉는것은 더욱 힘이듭니다. 
멀티탭의 경우에도, 작년에 비해 그 수가 적은것 같습니다.

그래서 2가지의 제안을 합니다.
1. 멀티탭의 추가 구매
2. 연장학습 자리의 경우, 기숙사 홈페이지에서 신청한 자리대로 앉을 것. 
    (신청하는 사람은 있지만, 대부분 지켜지지 않는것 같습니다.)

#### 제안 사항
- [x] 연장학습 신청석 착석
- [x] ~~멀티탭 추가 구매~~ (기존 멀티탭 제공)

**Comment by kyle-seongwoo-jun** [comment]
동의합니다. 저도 연장학습하면서 많이 느낀 부분입니다.

**Comment by SongKJ00** [comment]
멀티탭의 경우, 김광환선생님께서 작년에 기숙사 자습실에서 워낙 학생들이 사용하고 정리를 하지 않아 기숙사에서 제공하던 멀티탭을 제공하지 않기로 결정한 것으로 알고 있습니다.
현재 김광환선생님께서는 학습실에서 개인 멀티탭 사용은 허용한 상태입니다.

**Comment by hojak99** [comment]
멀티탭을 사용하고 난 학생들이 정리를 하지 않은 것도 잘못이지만 자습실 청소하는 친구들이 멀티탭을 정리해야 하는 것 아닌가요? 멀티탭 정리도 그렇고 쓰레기 문제 때문에 상점 봉사하는 친구들이 있는 것인 줄 알았네요

**Comment by u-dair** [comment]
처리 방식이 대단히 극단적이라고밖에 생각할 수 없네요. 멀티탭을 정리를 하지 않는다면 상점 봉사를 통해
 기존 학습실을 청소하는 친구들에게 멀티탭 정리를 시키거나 사감실로 회수를 시킬 수도 있고 여러 좋은 해결 방법들이 많은데 왜 항상 근원을 차단하려고만 할까요.. 그로 인해 생기는 부작용은 생각도 안 하는 것 같네요.

**Comment by kyle-seongwoo-jun** [comment]
정리를 하지 않은 학생들의 잘못도 있다고 생각합니다.

일단 회의 결과, 학생들이 우선적으로 멀티탭을 정리하되 정리되지 않은 자습실 청소당번이 정리하고 멀티탭을 정리하지 않아 적발된 학생은 제제조치를 가하도록 정하였습니다. 

시행될 때, 공지하겠습니다.

**Comment by kyle-seongwoo-jun** [comment]
@graykick 6월 12일부로 기숙사내 멀티탭 대여를 시작했습니다. [참고](https://www.facebook.com/dsmfriendship/posts/1394578083942619)

**Comment by kyle-seongwoo-jun** [comment]
@graykick 신청한 자리에 다른 학생이 앉아 있는 경우, 신청한 자리라고 말하여 신청한 자리에 앉으면 되겠습니다.
