### ISSUE TITLE
기숙사 벌레 문제

### ISSUE THREAD

**Issue by BGMina** [DSM-HS/student-council#23]
우리 대마고는 뒤에 산이 있다보니 자주 벌레와 마주치고 있습니다. 기숙사를 환기 시키기 위해 창문을 열어놓고 가면 방충망이 있어도 벌레가 들어오고, 최근에는 기숙사 문의 아래에 있는 틈 사이로 오기도 합니다. 그래서 기숙사마다 창문 틈이나 문 틈에 문풍지를 붙여 주셨으면 좋겠습니다. 난방 효과도 높아질 것이고 틈이 막혀서 벌레가 잘 들어오지 않을거란 생각에 학생회에 건의 해봅니다.

#### 제안 사항
- [ ] 기숙사 내 창문틈이나 문틈에 문풍지 붙이기

**Comment by SongKJ00** [comment]
지난 몇 주 동안 벌레가 들어오는 근본적인 원인에 대해 생각해 봤습니다. 
3층과 4층 기숙사 복도를 돌아다니면서 복도 창문이 방충망도 없이 열려져 있는 것을 수차례 보았습니다. 
벌레가 들어오는 원인은 물론 여러가지가 있겠지만 학생들이 애초에 복도 창문을 방충망도 없이 열어놓고 방치하는 것이 어느 정도 큰 문제라고 생각합니다. 윗 분의 의견도 일리 있는 얘기지만 학생들이 먼저 복도 창문을 잘 단속하는 것이 먼저라고 생각합니다.
