### ISSUE TITLE
2층 남자화장실 배수문제

### ISSUE THREAD

**Issue by AshtonYoon** [DSM-HS/student-council#24]
창의관 2층 남자화장실 세면데 두 곳 모두 배수가 원활하지 않아 양치때문에 상대적으로 사람이 몰리는 아침시간, 각종 오물이 내려가지 않은 물에 섞여있어 미관상 좋지 않아보입니다. 배수관 공사 진행을 논의해주시면 감사하겠습니다

**Comment by SongKJ00** [comment]
검토하겠습니다.
