### ISSUE TITLE
학교 자판기 비치 관련 건

### ISSUE THREAD

**Issue by rscarrera27** [DSM-HS/student-council#25]
현재 기숙사에만 자판기가 설치되어있고 학교에는 자판기가 설치되어 있지 않습니다. 
운동후나 체육 활동 후 부족한 수분이나 당분, 미네랄을 섭취하기 위해
 **이온음료나 아이스티 등**
을 판매하는 자판기가 설치되거나 우정관 자판기 한개를 옮겨 설치해 주시면 좋겠습니다.

## 제안
- [x] ~~교내 음료수 자판기 설치~~ (기각)

**Comment by kyle-seongwoo-jun** [comment]
창의관내 자판기 설치는 쓰레기 처리 문제, 예산 상의 문제를 비롯한 여러 문제들로 인해 어려울 것 같습니다.

보온병을 마련하여 음료를 담아 가져오는 것은 괜찮습니다.
