### ISSUE TITLE
휴대폰 걷는 방법에 대해 좋은 방법이 아니라 생각합니다.

### ISSUE THREAD

**Issue by BGMina** [DSM-HS/student-council#27]
예고도 없이 갑자기 휴대폰 걷는 방법을 개인 사물함이 아닌 바구니에 같이 넣어 보관하도록 변경 되었습니다. 저는 이 방식이 4가지 근거를 들어 반대 합니다.

#### 근거 
1. 바구니에 넣다가 분실, 파손 되는 휴대폰이 있을 수 있음.
2. 7시 25분경 부터 휴대폰을 가져갈 수 있다고 했는데, 7시~7시 20분에 등교하여 미리 공부하는 학생들은 휴대폰을 가져갈 수 없음.
3. 핸드폰 내는 시간이 늦어 빨리 내고 공부하고 싶은 선배님들, 친구들이 불편을 느낀다.
4. 폰 내는 시간에 다 같이 3층 피트니스 센터에 모여 폰을 내서 주변이 혼잡함.

p.s 다른 근거가 있다면 꼭 올려 주셔서 고칠 것은 고치고 유지할 것은 유지하도록 했으면 좋겠습니다

**Comment by kyle-seongwoo-jun** [comment]
저희도 공지 받은 게 없어 당황스럽네요 😓 일단 빠른 시일 내에 선생님과 이야기 해보겠습니다

**Comment by ghost** [comment]
이런 식으로 휴대폰을 걷어가실 거라면 파손, 분실시에는 학교측에서 책임을 져 주세요.
바구니에 휴대폰 걷는건 초등학교때 1년정도 빼고는 제출한 기억도 없네요.
너무 구시대적인 방법이 아닌가 합니다.

**Comment by ghost** [comment]
공부하기에 가장 좋은 환경을 구축하는 것이 학교의 목적이지, 남에게 피해도 안주고 학습과 큰 관련도 없는 휴대폰 규제 강화는 학교에서 진행해야 할 바가 아니라고 사려됩니다.

**Comment by ghost** [comment]
이런 것 보다는 개인용 학습실 구축이나 다른 학습환경 향상등을 학교에서 지향해주었으면 하는 바램입니다.

**Comment by u-dair** [comment]
우선, 휴대폰을 걷는 것 자체는 3년간 이상 없이 시행되던 규칙이라 그러려니 합니다. 하지만, 기존에 학생회에도 미리 공지하지 않고 (이는 위에 Nuwanda22님이 증명해주셨습니다.) 당일에 공지하여 시행했다는 사실 자체가 상당히 유감스럽습니다. 휴대폰을 걷는 것은 모든 학생에게 영향을 미치는 일이고, 당연히 사전에 이러이러한 일이 있을 것인데, 너희들 생각은 어떠냐? 이렇게 미리 언질을 하고 공지를 해주셨으면 이렇게까지 불만이 터져나오지는 않았을 것입니다. 이럴거면 학생회는 왜 만들었으며, 자치회는 또 왜 만들었는지 모르겠습니다. 학생의 입장을 대변하고 회의의 결과를 학생들에게 알려주어야 할 두 단체는 제 기능을 하지 못하고 있다고밖에 생각이 되지 않습니다.

또, 이슈를 열어주신 분의 말씀처럼 바뀐 휴대폰 규정에는 기존에는 없던 부작용이 따를 수 있습니다.
휴대폰을 걷고, 다시 배포하는 과정에서 휴대폰에 파손이 생길 경우 책임은 누구에게 있는가? 휴대폰을 걷는 상점 봉사 친구들? 아니면 애초부터 잘 부서지는 휴대폰을 낸 학생 책임? 아니면 이런 규정을 계획한 사감부 측? 저희는 아무것도 모릅니다. 새로운 규정을 실시할 때에는 이런 부분부터 확실히 해 주셔야 하는데, 기존 규정을 뒤흔드는 새로운 규칙이 나왔음에도 많이 미흡하다고 생각합니다.

또 기존 자율적으로 휴대폰을 내던 시간에서 강제적으로 휴대폰을 내야 하고, 또 본인이 직접 와야 하니 3학년들은 점호 끝나고 내면 되지만 1-2학년은 점호 끝나고 약 5-10분 정도를 기다려야 휴대폰을 낼 수 있습니다. 안 내면 뺏기고, 낼 때에는 기다리느라 시간 낭비.  비효율의 극치를 달린다고 할 수 있습니다. 이는 휴대폰을 다시 배포받을 때에도 마찬가지입니다. 또 장소 자체가 좁은 문제도 있죠. 이미 운동을 하는 친구들로 혼잡한 피트니스 센터인데, 기존 자신 노트북 사물함에 넣는 쾌적한 방법을 버리고 바닥에 바구니를 깔아 지정된 장소에 자신의 휴대폰을 놓는다... 바구니 자체가 잡아먹는 공간도 크고, 실수로 넘어지거나 바구니를 밟는다? 순식간에 몇백만~몇천만원이 저세상으로 날아갑니다.

**Comment by u-dair** [comment]
그렇게 걷어진 휴대폰을 보관하는 캐비넷도 문제입니다. 붙박이처럼 바닥이나 벽에 고정된 형태인 것도 아니고, 가뜩이나 유동 인구 많은 3층 피트니스 센터인데, 캐비넷이 운동하던 중 누군가의 실수로 넘어지면 그 안에 있는 휴대폰들이 멀쩡할까요? 운이 좋아서 멀쩡할 수도 있지만, 대개의 경우 액정이 부서지는 것에서 시작해 심할 경우 원래 곧게 펴져 있는 휴대폰이 졸지에 2G폰이 되는 경우도 발생할 수 있습니다. 폴더처럼
 굽어져서요. 물론 이는 발생하기 극히 어려운 상황이지만, 이런 사태가 일어날 경우 발생하는 금전적 피해는 어마어마하겠죠. 단순 계산으로 휴대폰 하나가 평균 60만원 정도 한다고 하면, 전체 학교 남학생수인 180명 * 60만원 = 1억 8천만원이 순식간에 날아갈수도 있습니다. 여학생까지 포함한다 하면 1억 4천 400만원이네요. 확률이 희박하다 하더라도, 이러한 상황에 대한 대비는 되어 있어야죠.

**Comment by u-dair** [comment]
따라서, 본 규정을 유지할 경우
하나, 학교 측에서는 학생의 금전적 손실에 대한 배상 규정과 책임을 확실히 해야 한다.
둘, 혹시 발생할 수 있는 금전적 손실을 막기 위해, 캐비넷과 바구니에 있는 휴대폰이 파손될 여지를 최소화해야 한다.
셋, 최소한 이렇게 학생 전체에게 영향을 끼치는 규정을 만들 때, 최소한 시행일로부터 2주일 전에 미리 공지를 해야 한다.
넷, 휴대폰을 내는 시간을 자율화하거나, 시간 낭비는 되지 않게 운용해야 한다.
다섯, 학생에게 영향을 주는 규정을 변경할 경우, 학생회와 자치회 역시 회의에 참여하게 하여 그 결과를 공지할 수 있게 한다.

**Comment by jychoi415** [comment]
아침에 7시25분부터 40분까지 휴대폰을 가져가지 않으면 그 날은 아예 휴대폰을 밤 9시 20분까지 보지 못하는 것도 좀 아닌 것 같습니다.

**Comment by ghost** [comment]
학교측에서 무언가를 진행할때 생각을 좀 하고 진행해주세요.
누가 봐도 무리가 있었던 규정입니다.

**Comment by SongKJ00** [comment]
아멘
