### ISSUE TITLE
여름철 냉방 문제

### ISSUE THREAD

**Issue by rscarrera27** [DSM-HS/student-council#28]
학교에서 6월이 된다면 에어컨으로 냉방을 한다고 하였음에도 불구하고 냉방을 연기하고 있습니다. 수업시간에도 기숙사 방에서도 더위가 심각한데 냉방을 하였으면 좋겠습니다

**Comment by kyle-seongwoo-jun** [comment]
현재 학교와 기숙사에서 에어컨을 가동 중입니다. 정확한 가동 기준을 확인하고 말씀드리겠습니다.

**Comment by kyle-seongwoo-jun** [comment]
기숙사내 에어컨 가동시간은 오후 10:30 ~ 12:30, 오전 7:00 ~ 7:20입니다.

**Comment by kyle-seongwoo-jun** [comment]
교내 에어컨 가동시간은 점심시간부터 오후 7시까지로 파악됩니다.

@Lewisxyz000 답변되셨나요?
