### ISSUE TITLE
정규수업 中 컨퍼런스 참여 문제

### ISSUE THREAD

**Issue by SongKJ00** [DSM-HS/student-council#29]
최근 본교에서 정규 수업을 하는 평일에는 컨퍼런스 참여가 불가능하게 되었습니다.  
이런 결과에 따른 본교 학생 여러분들의 의견과  그  근거 및 이유를 작성해주시면 감사하겠습니다.
작성하신 글은 추후에 큰 도움이 될 것입니다.

**Comment by SayBGM** [comment]
체험학습은 교실 안에서가 아니라 교실 밖에서도 교육활동을 실시할 수 있다는 전제 하에 진행되는 학습활동이다. 자연을 체험하거나, 역사 유적지 등 다양한 문화를 접하고 자신이 직접 체험하는 것을 통해 실제성있는 교육을 하기 위한 목적으로 만들어졌고, 현재까지도 진행되고 있는 프로그램이다.

네이버에서 나오는 현장체험학습에 대한 글입니다.

선생님들 물론 정규수업이 중요할 지도 모릅니다. 하지만 우리학교는 마이스터고인 만큼 직접 찾아가서 더 많은 경험을 하는 것이 중요하다고 생각합니다.  더 많은 체험이 학생들에게 더 많은 목표를 만든다고 생각합니다. 
그리고 불미스런 일로인해서 구루터 특강의 규모가 축소 되었습니다. 그렇기 때문에 특강을 들을 수 있는 기회가 줄어들었다고 생각합니다. 특강을 듣고는 싶지만 구루터 특강이 없는 지금 학업등에 의해서 들을 수 있는 기회가 줄어들었습니다. 지금의 '컨퍼런스 참여를 이유로 현장체험학습 신청 불가' 조치는 좋지 않은 결과를 불러올 수 있다고 생각합니다.

**Comment by ghost** [comment]
웃기는군.

**Comment by CHANMYUNG** [comment]
9월 11일 관련된 문제로 선생님과 꽤 오랜 시간 대화를 나누었고 결론은 이러했습니다.
- "무분별한 현장체험학습으로 인한 부작용이 있었다."
- 그건 그 학교고 우린 우리 학교다. (타 소프트웨어 관련학교의 세미나&컨퍼런스 현장체험학습과 BOB&소프트웨어마에스트로와같은 위탁교육에 대한 제도를 고려하고 내린 결정이냐는 물음에)
- 위탁교육을 들으러감으로써 학교 정규 교과과정을 빠져놓고 이를 출석으로 인정해달라는건 말이 안된다. (BOB&소마와같은 위탁교육에 대한 말씀, 이 부분은 저도 어느정도 동의합니다.) -> 긴 현장 체험학습은 안되고 짧은 하루짜리 교육을 들으러 가는게 되는건 불공평하다.(??) -> 따라서 둘 다 금지한다.(???) (교장선생님의 결정)

제 생각은 이렇습니다.
- 말씀하신 '무분별한 현장체험학습으로 인한 부작용'이 무엇인지 공개해주셨으면 좋겠습니다. 하루아침에 느닷없이 신청서 양식을 강화하고 (이 부분은 어느정도 이해가 갑니다만..) 세미나 & 컨퍼런스 참여를 전면 금지하는건 학생들의 입장을 전혀 고려하지 않은 정책이라고 생각합니다.
- 무슨 사건사고만 발생하면 제한하고 / 금지하기 급급한 학교의 태도가 문제인 것 같습니다. (위에서 언급한대로, 어떤 사건 사고인지 알려주지조차 않습니다.)
- 학생들의 다양성을 인정하지 않고 틀에 박힌 교육과정에 맞추어 개조하려는 모습이 개탄스럽습니다.
- 기존 교칙에 현장체험학습 허용함을 명시하고 있음에도 불구하고 교장선생님의 이런 독단적인 결정은 학생들의 반발을 불러일으킬 뿐입니다.

**Comment by alsrbaa13** [comment]
이 문제에 대해서 선생님을 통해서 입장을 들었는데 선생님들의 의견을 종합하면
1. 의미없는 현장체험학습 신청이 많다. 
2. 현장체험학습의 안좋은 결과를 초래하였다. 예) 현장체험을 가장한 연인들간의 여행, 외부기관을 나간다.(이는 개인적인 판단이 아닌 선생님을 통해 들은 얘기입니다) 
3. 현장체험학습 이후의 보고서나 사진이 부적절하거나 불충분하다.

이러한 선생님들의 입장에 대한 저의 생각은 이러합니다.
1. 의미없는 현장체험학습를 막고자 신청서의 내용이 풍부해야하거나 선생님간의 간단한 담소를 통해 설명을 드려서 방지한다. 또는 3일전에 신청서를 내야하는 기간을 지키지않고 신청한다면 거부하는 등의 사전에 계획이 되어야된다고 생각합니다.
2. 물론 안좋은 결과를 초래하지만 이에 대한 공지도 없었고 선생님들간의 훈계들도 없었습니다. 예로 교장선생님이 새롬홀에 모였을 때 따끔하게 얘기하셨을 때와 같은 훈계들이나 공지들이 없었는데 단지 급급하게 막는 학교의 대처의 문제가있는 것 같습니다.
3. 3번의 내용은 지금처럼 보고서의 내용을 추가를 하거나 불이익을 가하는 등 단체처벌보다 개인처벌을 위주로 해야한다고 생각합니다

**Comment by curaai** [comment]
저는 학교에서 컨퍼런스를 가지 못하게 하여 생기는 문제점에 대해 말하겠습니다.

**학교에서 컨퍼런스 및 각종 교육** 등을 가지못하게 제재하는 경우 
- 학교에서는 컨퍼런스나 각종 교육에서 가르쳐 주는 내용을 거의 가르쳐주고 있지 않다. c#, swift, 안드로이드, 웹 프론트 및 서버, 머신러닝, 그래픽스 등 이러한 내용들을 2학년 때는 제대로 배우지도 않으며 만약 혼자 독학을 하지 않고 학교 교육에만 따르는 경우에는 실무의 역량이나 기술들을 절대 낼수 없다고 생각합니다. 
- 그런 여러 대외 행사 참여를 통해 다양한 네트워킹과 현업 개발자의 팁, 대화, 상담 그리고 취업연결의 기회까지 가지고 있다고 생각합니다. 하지만 이런 것들을 제재 하게 될경우 이런 기회들을 놓치게 되는건 학생과 학교 모두 크나큰 후회와 손해가 될것입니다.

**Comment by SongKJ00** [comment]
여러 대회 참여라는 것이 정확히 대회(competition) 참여를 말씀하시는 건가요 아니면 대외 행사 참여를 말씀하시는 것인가요?

**Comment by curaai** [comment]
대외 행사요 수정했습니다

**Comment by rscarrera27** [comment]
안녕하세요 1학년생입니다. 저는 머신러닝을 공부하고 있는 중이지만 학교에서 가르쳐 주는 것에는 머신러닝을 공부할 수 있는 기회가 존재하지 않고 독학하려고 해도 좁은 분야라 공부하기가 쉽지 않고 세미나, 실습 같은 기회로 사람들을 만나고 새로운 것들을 배우거나 알게 되는 기회가 됩니다. 그런 의미에서 세미나를 신청했지만 최근에 학교의 새 정책으로 인해 거부당했습니다.  따라서 저는 신청한 실습 교육을 취소해 달라고 주최자 분에게 이메일을 보내어 사정을 설명드렸습니다. 그러자 주최자 분께서 저에게 실습 조교로 참가를 시켜 주시겠다고 하셨지만 학교에 문의해보니 제가 발표를 하러 가든 조교를 하러 가든 보내줄 수 없다고 합니다... 

또한 코드 스프린트(모여서 오픈소스 컨트리뷰션 하기)같이 수상이 없는 대회(?) 들도 참가가 불가하다고 합니다... 

머신러닝, 그래픽스 등 학교에서 배울 수 없는 분야를 공부하려는 학생들은 어떻게 자기 분야의 전문가들을 만나야 할지 막막해 지는 것 같습니다.

**Comment by SpiralMoon** [comment]
현장실습중인 저에게는 해당되지 않는 이야기이지만, 소중한 후배들한테는 해당되는 이야기이니 안타깝네요.

우선 2017년 9월 14일자로 학교에서 공고한 [개인 현장체험학습 시행규칙]이란 제목의 종이에는 다음과 같이 쓰여 있습니다.
`-----------------------------------------------------------------------------------------------------`
# [개인 현장체험학습 시행규칙]
대덕소프트웨어마이스터 교무부 2017.09.14.
## 1. 개인현장체험학습 규정에 따라 허가
가. 가정의 경/조사 및 행사
나. 부모와 함께하는 여행
다. 대회 참여(대회주최 기관과 취지에 따라 승인 여부 판단이 필요함)
라. 교육인턴(방학 중에 실시하나 회사의 사정에 따라 전후 1주일 정도허가 - 산학협렵부 협조)
마. 현장실습으로 인한 준비(2~3일 이내)
바. 우리학교 교육과정 내용과 일치하고 부모님과 동행하는 세미나, 컨퍼런스, 전시회
    - 출발과 도착시 학부모 동행이 원칙.

## 2. 개인현장체험학습 불허
가. 우리학교 정규교육과정 운영기간과 겹치는 교육
나. 학부모 동행 없이 학생 개인 자격으로 참여하는 세미나, 컨퍼런스, 전시회
다. 학부모 동행 없이 학생 혼자 하는 여행

## 3. 학교의 지원 대책
가. 세미나, 컨퍼런스 등은 외부전문가를 초빙하여 우리학교 수준에 맞는 특강실시
나. 학생전체에게 필요한 전시회는 학교에서 추진하고 학과별로 필요한 전시회는 수업시수가 허락하는 범위 내에서 학과단위로 추진.
다. 전공동아리 등 멘토 지정하여 운영(구루터 특강, JumpUp 캠프)
라. 전문성을 갖춘 산학 협력교사 확보

## 4. 개인현장체험학습 절차 및 결과처리
가. 3일전 신청서 제출 -> 허가 -> 체험학습 실시 -> 3일 이내 보고서 제출
    1) 학교장의 승인 없이 실시한 체험학습 또는 체험학습 후 3일 이내 보고서를 제출하지 않은 경우 무단결석 처리.
    2) 보고서 내용이 계획서의 내용과 다른 경우 무단결석 처리
나. 보고서는 형식에 따라 작성하고 증빙서류 첨부하여 제출
다. 사전에 승인된 대회, 세미나, 컨퍼런스, 전시회 등의 참여시 "학생 대회 활동 확인서"를 보고서에 첨부하여 제출.
`-----------------------------------------------------------------------------------------------------`
한 번이라도 DSM 학생의 입장에서 생각해보았더라면 위와 같은 끔찍한 결론은 나오지 않았을 것이라고 생각합니다.
위의 규정에 대해서 각 항목마다 제 개인적인 의견을 끄적여 보겠습니다. 아래부터는 제 의견입니다.
`-----------------------------------------------------------------------------------------------------`
## 1. 개인현장체험학습 규정에 따라 허가
나. 부모와 함께하는 여행
`부모님과 함께하는 여행을 허가한다고 쓰여있는데, 왜 정작 정규교과수업을 진행하지 않는 방학기간에 여행을 간다고 하면 허가를 안해주는지 모르겠습니다?`
다. 대회 참여(대회주최 기관과 취지에 따라 승인 여부 판단이 필요함)
`주최 기관과 취지에 따라 승인 여부를 판단한다는 뜻은 즉, 규모가 크고 이름있는 대회만 보내준다는 뜻으로밖에 해석되지 않습니다. 물론 주최측이 불분명한 단체이거나 개인인 경우에는 안보내주는게 맞다고 생각합니다만, 규모가 작은 대회라도 보내줬으면 좋겠다는 생각입니다. 누구나 출발점이 다르고 개인의 실력과 관심분야도 다르며, 자신감과 도전정신의 레벨도 다르기 때문에 다양한 규모/형태의 대회를 학생이 직접 선택해서 가는 것은 '스스로가 성장하는 단계'임을 칭찬해주어야지, '승인 여부를 판단할 대상'이 되어서는 안된다고 생각합니다. 본인의 경우에도 보잘 것 없는 대회부터 시작해서 큰 대회까지 도전한 케이스입니다.`
마. 현장실습으로 인한 준비(2~3일 이내)
`이건 굉장히 필요하다고 느꼈습니다. 좋습니다.`
바. 우리학교 교육과정 내용과 일치하고 부모님과 동행하는 세미나, 컨퍼런스, 전시회
    - 출발과 도착시 학부모 동행이 원칙.
`이 규정이 도대체 어떻게 발의되었고, 통과되었는지 정말 이해가 되지 않습니다. 규정을 이런 식으로 만드시면 그냥 현장체험학습 가지 말라는 소리가 되는 것입니다. 교육과정에 없는 게임개발/머신러닝/창업/AWS 등과 관련된 행사는 못가는 겁니까? 세미나랑 컨퍼런스를 왜 부모님과 같이 가야합니까? 현장에서 배우고 느끼는 사람은 부모님이 아니라 학생입니다. 부모가 동행할 필요가 전혀 없습니다. 더군다나 DSM은 전국 각지에서 온 학생들로 이루어져있는데 컨퍼런스 한 번 참여하려면 대한민국
 어딘가에서 바쁘게 일하시고 계신 부모님이 학교까지 와서 같이 출발/도착해야 한다는 것은 참으로 어이가 없고 말도 안됩니다. 부모님들은 그렇게 한가한 사람들이 아닐뿐더러, 1학년 김형규 학생은 컨퍼런스 갈 때마다 부모님이 제주도에서 비행기타고 대전으로 와야합니까? 부모님이 양쪽 다 안계시는 학생은 컨퍼런스 꿈도 못 꾸겠군요?`

## 2. 개인현장체험학습 불허
가. 우리학교 정규교육과정 운영기간과 겹치는 교육
`정규교육과정 운영기간과 겹치더라도 학교보다 더 수준/질이 높은 교육을 받을 수 있다면 보내줘야 한다고 생각합니다. 대표적으로 BOB가 있는데 보안과에서 가르치는 커리큘럼보다 훨씬 우수합니다. 보안 전문가는 절대로 학교 교육 과정만으로는 키울 수 없습니다.`
나. 학부모 동행 없이 학생 개인 자격으로 참여하는 세미나, 컨퍼런스, 전시회
`위에 서술`

## 3. 학교의 지원 대책
가. 세미나, 컨퍼런스 등은 외부전문가를 초빙하여 우리학교 수준에 맞는 특강실시
`'우리학교 수준에 맞는 특강'이라는 문장이 도대체 무슨 뜻인지 모르겠군요. 선생님들께서는 기존의 세미나/컨퍼런스가 DSM 학생들은 이해할 수 없는 높은 수준의 행사라고 생각하는 것 같습니다? 개인마다 이해도가 다른 것은 사실이지만, 우물 안 개구리가 밖으로 나가기 위해서는 이해가 부족할지라도 외부 세미나/컨퍼런스에 참여하며 견문을 높이는게 중요하다고 생각합니다. 외부전문가를 교내로 초청해봤자 고등학생 수준에서 달라지는 것은 없다고 생각하며 학생들에게 별 효과도 없다고 생각합니다. 학생 개개인의 한계를 학교가 두는 것 같아 속상합니다.`
나. 학생전체에게 필요한 전시회는 학교에서 추진하고 학과별로 필요한 전시회는 수업시수가 허락하는 범위 내에서 학과단위로 추진.
`학생에게 무엇이 필요한지는 학교가 아니라 학생 개인이 더 잘 압니다.`
다. 전공동아리 등 멘토 지정하여 운영(구루터 특강, JumpUp 캠프)
`구루터 특강은 현재 운영도 안하고 있고, 전공동아리 멘토도 학생들이 직접 구하러 다니는 마당에 도대체 뭐가 '학교의 지원 대책'입니까?`

## 4. 개인현장체험학습 절차 및 결과처리
가. 3일전 신청서 제출 -> 허가 -> 체험학습 실시 -> 3일 이내 보고서 제출
    1) 학교장의 승인 없이 실시한 체험학습 또는 체험학습 후 3일 이내 보고서를 제출하지 않은 경우 무단결석 처리.
    2) 보고서 내용이 계획서의 내용과 다른 경우 무단결석 처리
`7일전에서 3일전으로 바뀐 것은 매우 좋습니다.`
나. 보고서는 형식에 따라 작성하고 증빙서류 첨부하여 제출
`증빙서류는 철저하게 검증해야한다고 생각합니다. 좋습니다.`
`-----------------------------------------------------------------------------------------------------`
학생들의 의견이 전혀 반영이 되지 않은 것 같아서 아쉽습니다. 제발 이제는 학생들이랑 소통좀 했으면 좋겠습니다.

+ 시상식 참가하라고 공문 내려온적 있는데 학교에서 거절 당한적 있습니다. 덕분에 상장이랑 감사패를 택배로 받았습니다 하하하
+ 솔직히 실력 안되는 친구들은 외부 활동 나가서 인맥이라도 쌓아야 취업에 유리합니다.
+ 학생들을 학교에 묶어둔다면 교장 선생님께서 원하시는 아키텍트는 커녕 대체 가능한 코더 밖에 안됩니다.
+ 김형규 학생은 컨퍼런스 가려면 진짜로 부모님이 제주도에서 비행기타고 오셔야 하나요?

**Comment by usernameSplash** [comment]
우선 학교측의 입장은 컨퍼런스와 세미나를 불가능하게 막는 것이라고 생각됩니다.
전국의 학생들이 모인 DSM이란 특성과, 맞벌이 가정이 많은 현실 속에서 학부모의 출발 및 도착의 동참은 현실적으로 어렵다는 것을 학교측에서도 잘 알고 있을 것이라고 생각합니다. 
선생님들의 말씀에 따르면 컨퍼런스 및 세미나를 부모님의 동참 하에 참석할 수 있으므로 막지는 않았다는 의견인데, 대부분의 학생 여러분께서 생각하시는 대로 **학교에서 세미나 및 컨퍼런스를 막은 것이 맞다고 사료됩니다.**

학교와의 소통 및 불통 논란을 말하기 앞서, 학교측에서 이렇게 컨퍼런스와 세미나를 불가능하게 막은 이유는 과연 무엇일지 성찰해보아야 한다고 생각합니다. 제가 듣기로는 현장체험학습을 악용하는 사례가 종종 있다고 들었고, 학교에서 규제를 한 대표적인 이유 또한 이 때문이라고 들었습니다. 그래서 저는 세미나와 컨퍼런스를 원천적으로 막는 현 규제를 시행하는 것이 아닌, 현장체험학습 보고서 요구 수준 상향 및 **악용 처벌 강화**를 주장합니다.

저는 어차피 컨퍼런스와 세미나를 자주 나가지 않기 때문에 학교측의 규제에 큰 타격을 받는 측에 속하지는 않습니다만, 학교측에서의 문제해결방법과 그에 따른 대책이 비합리적이라고 생각하였기 때문에 위와 같은 글을 썼습니다.

제가 주장하고자 하는 바는 복잡한 것도 아니고, 현실성이 없는 것도 아닙니다. 단지 현장체험학습을 이용하여 뭔가 활동을 하고 왔으면 그에 따른 책임만 충실히 하자는 것입니다. 자유에는 항상 책임이 따릅니다. 이제까지의 악용 사례로 인해 현장체험학습에 대한 규제를 가한다는 학교측의 말도 일리가 있다고 생각합니다. 하지만 자유에 따르는 책임을 지지 않은 사례 때문에 **집단 구성원 전체가 피해를 받는 일**은 없어야 한다고 생각합니다.

따라서, 학생회 차원에서 학교 측으로 입장을 전달할 때, 학생 여러분이 원하는 바를 전달하되 우리도 그에 상응하는 책임을 다할 것을 약속해야 학교측과의 소통이 가능해진다고 생각합니다.

**Comment by 98ff98** [comment]
학교에서 만들어낸 새로운 규칙이 거주지역에 따라 학생을 차별하게 될 여지가 있는것 같다.

"컨퍼런스 세미나등에 참석할 때 무조건 부모님이 동행해서 다녀와야한다" 라는 규칙을 만든 것은 
규칙을 생각해낸 사람 스스로도 현실적으로 사실상 불가능하니 그냥 가지 말라는 뜻으로 만든 걸로 보이는데, 이 규칙이 특정 지역 거주 학생들에게 유리하다는건 생각을 못한건지 그냥 외면한건지 모르겠다.

 예를 들어서 거주지역이 대전권인 학생이 현장체험학습을 통해 서울에서 열리는 세미나에 참석할 경우
해당 학생의 부모님에게 발생하는 손해는 { 하루 연차사용 + 서울-대전 왕복 + 그에 따른 비용} 이며,
거주지역이 서울/경기권인 학생의 경우도 동일하다. 
 하지만 그외 지역에 거주하는 학생의 경우에는 부모님에게 발생하는 손해가 엄청나게 커진다.
만약 강원도에 거주하는 학생이 서울에서 열리는 컨퍼런스에 참석할 경우, 그 학생의 부모님은
{ 강원도<-->대전  600km + , 대전<-->서울 380km 총합 약 1000km} 를 하루동안 이동하셔야한다.
이게 정녕 사람의 머리에서 나올 수 있는 발상인지 궁금하다.  

원래 전국에서 학생을 모집함에도 그에 따른 배려는 눈꼽만큼도 없는 학교였지만... 
(ex. 귀가 시간을 하루전에 공지하여 경부선 표를 끊지 못해 귀가일 당일에 두 시간 더 일찍 귀가 할 수 있겠냐고 물어보자 표를 못구한걸 왜 남탓하냐면서 화내던 모 교사)

가면 갈수록 그 추태가 심해지고 있다...

**Comment by SpiralMoon** [comment]
그럼 1학년 김형규 학생은 컨퍼런스 갈 때마다 부모님이 제주도에서 비행기로 날라와서 데려가야합니까?
말이 되는 소리를 해야지 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by gohome0001** [comment]
# 허위 체험학습 방지

간단하게 예시를 들어보자

### 컨퍼런스

- 학생에게 도움이 된다
  -  해당 분야로 사람들도 만나고, 최신 동향 등 다양한 정보를 얻을 수 있는 좋은 기회이다.
- 그러나 학습에 있어서 필수적이라고 말하기는 힘들다.
- 정규 수업을 빼먹는 것은 학교에서 민감하게 생각하는 것들 중 하나이다.
- 컨퍼런스 간다 하면서 놀러가는 경우도 생길 수 있다.

### 12시 이후 무조건 소등

이번 사건과 크게는 관련없지만, 학습 시간 제한도 비슷한 경우라 생각한다.
- 학생에게 도움이 된다
  - 밤 늦게까지 노트북을 이용한 자습, 프로젝트를 가능케 하면, 학생이 사용할 수 있는 시간이 늘어난다.
  - 학생이 더 성장할 수 있는 기반이 될  것이다.
- 그러나 학습에 있어서 필수적이라 말하기는 힘들다.
- 자신의 컨디션을 생각하지 않고 늦게까지 하다가 학교 수업시간에 조는 경우가 많아질 수 있다.
- 늦게까지 놀면서 있는 학생도 있을 것이다.

## 결국에는..

### 학교 방침대로 한다면..
- 좋은 의도로 컨퍼런스를 가려 했으나, __부모님이 동반하기 어려운 경우 못 간다.__
- 학교에서 허위 체험학습을 막아도, 허위로 갈 사람은 가게 될 것이다.
- 학교에서 수업시간에 졸지 말라는 의미로 일찍 자라 하지만, 원래 자던 사람은 잔다.

결국 학교에서 악용사례 및 부정적 결과를 원치 않는다면, 이런식으로 막는 것은 의미없다 본다.
__오히려 좋은 의도로 활용하려는 사람들에게 피해가 간다.__

__악용, 부정적 결과에 대해서 책임을 지우면 되지, 좋은 의도를 갖은 학생들을 막으면 안된다.__
- 잠재적 '제도 악용자' 로 여기면 좋은 의도를 갖은 사람들이 피해를 본다 : 학생 불만
- 느슨하게 풀어주면 악용사례가 생긴다 : 학교 불만
- 서로 만족할수는 없을까?


### 보고서 철저하게 받기
- 참석을 입증할 만한 여러 사진들을 첨부해, 들은 강연에 대해 철저히 보고서를 작성하게 한다.

솔직히 보고서랑 사진 철저하게 검사하는것만 해도 악용 사례는 분명히 줄어들 것이라 생각한다.

# 정규 수업

정규수업을 빼먹어서 학교가 걱정하는건 이해하기 힘들다.
수업 빼먹어서 얻는 불이익은 학생이 자연스레 책임을 지고 있다.
결국에 __학교는 성적이 안 좋게 나오는 것을 걱정한다__ 고 본다.. ~아니면 도대체??~
그렇지만, __성적도 원래 관리 못하는 사람이 낮게 나온다.__
성적 관리했던 학생이 컨퍼런스 떄문에 성적 낮게 나올까봐 걱정할 필요는 없다고 생각한다.
학교에서 진정 이를 걱정한다면, 컨퍼런스를 막는게 아닌 성적 낮은 학생을 관리해야 한다.

--------------

솔직히, 지금 다루는 문제는 결국에 나타나는 결과가 좋으면 그만이라 생각한다.
컨퍼런스 갔다와서 실력 늘면 그만. 성적 알아서 챙기면 그만이지 쓸데없는 제제는 필요없다.
가짜로 컨퍼런스 가고, 성적 떨어지는 것에 대해 책임을 물으면 된다.
 
학교측에서 __그저 편하게 관리__ 하려는 이유만으로 좋게 활용될 수 있는 제도/방법들을 단순히 막는다면
정말 우리 학교가 좋은 학교인가?

**Comment by Lewisxyz000** [comment]
질문 비슷한 것이 하나 있습니다..
학교에서는 이게 과연 정규교육 과정 중 세미나 컨퍼런스를 가는 것이 싫은 건지 아니면 찬성하지만

**Comment by rscarrera27** [comment]
죄송합니다 실수로;;;

**Comment by gohome0001** [comment]
너무 장황하게 쓴거 같아서..

좋은 제도를 나쁘게 활용하는 사건 때문에 좋게 활용하려는 다수까지 제제받는게 합리적일까?
왜 연대책임을 묻는 것일까? 잘못한 사람만 제제하면 되는데.

잘못에 대해선 개인에게 책임을 묻고, 또한 학교가 우려하는 결과에 대해 개인에게 책임을 물으면 된다.
칼이 살인에 사용된다고 칼을 못쓰게 하나? 살인자에게 책임을 묻지.

학교가 물론 아예 못가게 한건 아니다. 학부모 동반이라는 조건 하에 갈수 있다고 한다 ^^
그렇지만 내 입장에서는 '왠만하면 가지 말아라'로 들린다. 
학교가 진짜로 컨퍼런스를 참여했나/안했나를 검증하기 위한 방법으로 채택한 것이 학생에게는
'왠만하면 가지 말라'로 들린다.
학교에서는 컨퍼런스 참여를 부정적으로 본다고 알아들으면 될 것 같다.

작년에는 안 이랬는데? 사건이 터지면 학교의 생각이 달라지나?
예전에는 필요에 따라 느슨하게 했고, 원래 이렇게 했어야 한댄다.
심지어 이 제도가 싫으면 학교를 떠나라고 한다.  
이래 두고 일방적 통보가 아니라는 둥..

### 학교

1. 학교가 무분별, 허위 체험학습의 사례를 근거로 들었음
2. 모든 교육은 학교에서 이루어지는게 원칙이라 함.
3. 부모 동반이 체험학습의 의도라며 이야기를 함.
4. 필요하면 학교로 강사를 부르라고 함.
5. 컨퍼런스의 수준이 높아서 학생들이 가도 얻는게 없을 것이다.

### 의견

1. 잘못에 대해 책임을 지워야지, 연대책임은 합리적이지 않다.

2-1. 자녀분 학원은 보내셨을지 의문이다. SW와 관련없는 내용도 아닌데, 장소만 다른 이유로, 학교 재량으로 할 수 있는 부분을 저런 사소한 것에 의미 부여해가며 막아야 할까? 

2-2. 사람들과 만나며 인맥 쌓는 것은 교육이라 말하기 어렵다. 즉 학교 외에서 이루어져도 되나보다 !

3-1. 여행을 가는 것에 염두를 두고 세운 제도라 그렇다고 생각한다. 일반 학교를 위해 생긴 제도를 똑같이 적용하는 것은 전공을 갖은 우리 학교의 특성을 보면 모순이 있다 생각한다.
3-2. 부모님이 시간내서 같이 가주실 수 있는 분이 얼마나 계실까? 그것도 전국 학생이 모인 학교에서.. 현실성 없는 대안이다.

4. 이건 좋게 활용되고 있었는데.. 컨퍼런스를 이로 대체할 수 있다 생각한다면, 학생들이 컨퍼런스를 가는 이유를 잘 생각해 보았으면 좋겠다.

5-1. 입학설명회, 뉴스 기사에서는 수준 높다고 굉장히 띄워주던데, 뭔가 이상하다.
5-2. 학생들이 컨퍼런스를 가려는 이유를 다시한번 생각해 보았으면 좋겠다.

**Comment by SongKJ00** [comment]
좋은 의견들 감사합니다. 최대한 빨리 해결하도록 노력하겠습니다.

**Comment by Splash3085** [comment]
@SongKJ00 지금 이 주제에 대해서 논의가 얼마나 진행중인지 알 수 있을까요
