### ISSUE TITLE
아침운동의 안정성 보증 및 개선

### ISSUE THREAD

**Issue by ghost** [DSM-HS/student-council#3]
아침운동의 목적성(물어보는 교사마다 다르게 말하기는 하지만)이 체력 증진에서 잠을 깨는 것을 바꾸어야함.
논문을 포함 신뢰할 수 있는 증빙자료 약 40여개가 있음

논리적인 반박의 내용

1. 아침운동을 시행하니 성적이 올랐다?
우선 성적이 올랐다는 이론은 하버드 대학 존 레이티 교수의 논문에 의거한 것인데, 문제는 이를 잘못해석한 것에 있다.
Spark에는 이런 내용이 있다. 
"기존 뇌세포의 기능을 강화하고 단기기억이 장기기억으로 고착되는 과정의 속도를 현저히 빠르게 한다" 라는 내용이 있는 건 사실이나, 이는 아침 운동이 아니라 운동의 이점에 대해서 서술된 것이고 이 내용 바로 뒤에 있는 내용인 "This also means that learning something new during exercise can generate neurotransmitter"라는 내용을 운동을 하는 동안 신경전달물질이 생성된다라는 내용이 아닌, 운동을 하는 시기로 잘못 해석 한 것이다.
민사고의 사례를 들어보자
민사고는 아침운동을 시행하고 8개월간 성적에 변화가 없었는데, 2학기 기말고사부터 지구과학을 제외하고는 대단히 쉽게 나왔다.
그덕에 평균성적이 모두 오르게 되었는데, 이를 '생로병사의 비밀에서는 아침 운동의 효과라고 말한다
여기서 문제는 인과관계가 있다는 논리적 배경이 없다.
게다가 민사고 재학중인 지인의 말에 따르면 전교생 468명중 3명을 붙잡고 물어봐서 성적이 올랐는지 물어봤다고 하는데, 시험이 쉽게 나왔으니 성적이 오르는게 당연한 일이다.
게다가 학교에서 보여준 영상에는 꼭 2년전에 아침운동을 시작한 것 처럼 말하는데, 1990년대부터 시작된 민사고의 전통이고, 2012~2014에 성적이 올랐다는 내용이기에 아침운동으로 인해 성적이 올랐다는 것은 더욱 신빙성이 없다.
따라서, 이런 식의 아침운동은 잠을 깨는데에 목적성을 두어야하고 체력 증진을 한다는 건 말이 안된다.
2. 아침운동의 강도
이번에도 민사고의 사례를 들어보자
민사고는 기온이 낮은 12월 부터 2월에는 시행을 하지 않고, 1학년떄는 검도 베기 300회, 2학년때에는 운동장 2바퀴 조깅, 3학년때에는 6분짜리 준비운동을 한다. 게다가 아침운동 시간도 ' 20 ~ 30분 ' 이고 아플시에는 반 강제적으로 아침운동에 참여하지 않는다.
이것도 아침운동치고는 꽤나 많은 편이다.
존 레이티 교수도 많은량의 운동은 역효과를 부른다고 지적한바 있다.
절대 운동장 5바퀴~8바퀴를 전력으로 뛰거나 검도를 50분씩 하는 짓은 안한다.
대덕대 운동장 한바퀴는 395m, 그리고 최소한으로 해서 5바퀴를 뛴다고 하면 1975m 즉, 2km를 시속 12km로 뛰게 되고 그 주파 시간이 대략 10분정도 인데, 이는 성인 남성의 최상위권이나 육군의 특급 병사 운동량과 비슷하다.(작년 선배들은 초인임에 틀림없다.)
이 운동량은 체력이 약한 사람 이나 저혈당인 사람은 자칫 기절 할 수도 있는 운동량이다. 그리고 가장 놀라운점은 이게 우리학교 아침운동에서 운동량이 가장 적은 것이다.
이러다 누가 다치면 책임 질것인가?
여기가 체육 중점 학교인가?
3. 아침운동의 필요성
학교측의 논리는 다음과 같다.
우리처럼 하루종일 컴퓨터를 많이 하는 사람들은 운동량이 월등히 적다. 따라서 운동을 해주어야 한다.(아침운동과 뇌의 인과관계는 이미 위에서 지적하였다.)
우선 컴퓨터를 많이 하는 사람이 몸이 많이 아픈 것은 사실이다.
그러나 그것은 운동량이 문제가 아니다.(놀랍지만, 프로그래머 직군의 운동시간은 평균 운동시간보다 10퍼센트 정도 더 많다.)
햇빛을 제대로 받지 못하는 문제가 크며 전자파를 근거리에서 많이 받기 때문이다.(너무 많은 논문이 있으니 심심하면 찾아봐라)
또한, 우리나라 고등학생의 평균 운동시간(70분)에 비해 우리 학생들이 근소폭 운동량이 적은 것은 동의한다.
그런데 그 이유하나만으로 1주에 250분의 추가 운동을 하는건 넌센스다.
그리고 아침에 검도나 야외 달리기를 하는 것은 몸에 매우 나쁘다.
검도는 근력운동인데, 저녁을 17시 30분에 먹고 12시간 넘게 공복 상태라서 혈당등이 크게 떨어진 상태에서 근력운동을 하면 몸의 근력량이 줄어들게 된다. (이 또한 논문이 많다,)
분명히 다과실이용을 하면 된다고 할 것인데, 이는 가난한 학생들에게는 반 강제적으로 지출을 유도하는 행위이다.
아침운동으로 검도를 할 것이라면 학교에서 아침운동 전에 간식을 제공하라.
야외 달리기또한 몸에 좋지 않다.
아침시간의 대기상태는 하루 중 가장 안좋고, 뇌의 활성화가 이루어 지지 않은 시각이기에 사고가 유발되기 매우 쉽다.
게다가 위에서 지적한 바와 같이 운동량이 미치도록 많기 때문에 매우 위험한 행위이다.
아침운동의 부정적인면에 관한 논문은 너무나도 많기에 다 서술하기는 귀찮아서 생략한다.
4. 실제로는 많은 학생들이 운동량이 적다고 주장한다?
학교에서는 아침운동의 강도에 대한 익명투표가 안되는 이유는 분위기에 휩 쓸려서 많다고 하지만, 실제로는 적다고 주장하는 학생들이 많기 때문이라고 한다.
... 할 말 없다.
익명이 뭔지 모르는 걸까?
5. 체력이 낮은 학생이 더 운동을 많이하는 아이러니함
달리기 운동과 걷기 운동의 운동량의 차이는 10퍼센트 내외이다. 그리고 운동량은 거리나 시간에 비례하는 것은 잘 알고 있을 것이다.
B조나 걷기조는 체력이 약한 학생들이 있는 조인데, 왜 운동량이 더 많아야만 하는 것인가?

#### 제안 사항
- [ ] 아침운동의 목적을 체력 증진에서 기상으로 바꿀 것

#### 추가 의견
- [ ] 아침운동을 점심이나 저녁시간으로 이동
- [ ] 아침운동 없는 날 개설

**Comment by kyle-seongwoo-jun** [comment]
### 제시 안건
- [ ] 아침운동의 목적을 **체력 증진**에서 **기상**으로 바꿀 것

### 안건 제시 근거
* 아침 운동이 성적 향상에 도움을 주는 주장은 신빙성이 떨어짐
* 체육 중점 학교가 아니지만 현재 아침 운동의 강도가 건강에 위협을 끼칠 우려가 큼
* 컴퓨터 중점 학교라고 운동량이 적다는 생각은 편견임
* _"아침 운동 운동량이 적다고 말하는 학생이 많은 이유가 분위기에 휩쓸리기 때문이다."_ 라는 주장에는 근거가 없음
* 오히려 체력이 더 낮은 학생이 더 많이 운동함

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 맞게 정리되었는지 확인 부탁 드립니다.

**Comment by ghost** [comment]
아침 운동 운동량이 적다고 말하는 학생이 많은 이유는 분위기에 휩쓸리기 때문임 -> 아침 운동 운동량이 적다고 말하는 학생이 많은 이유는 분위기에 휩쓸리기 때문임 이라는 주장은 근거가 없음

수정 부탁드립니다.

**Comment by ghost** [comment]
그리고 안건 제시하실때 구체적인 근거를 제시하셔야 합니다.
주장만 늘어놓는것은 글의 신뢰도와 전문성을 크게 떨어트립니다.

**Comment by ghost** [comment]
강도가 높음도 강도가 건강에 위협을 끼칠 우려가 큼으로 수정해주세요.

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 확인 바랍니다.

**Comment by ghost** [comment]
넵 확인했습니다. 감사합니다.

**Comment by Dongjun-Jii** [comment]
"논문을 포함 신뢰할 수 있는 증빙자료 약 40여개가 있음"이라고 했는데 저도 이거 읽고 찾아보고 싶은데 링크좀 주실 수 있나요.

**Comment by jaemin-im** [comment]
아침운동의 시간을 점심시간같이 학생들이 다 깨어있을 때 해도 괜찮을 듯 한데, 선배님들은 어떻게 생각하시는지 알고 싶습니다.

**Comment by Kinter** [comment]
그러면 아침운동이 아닌게 되어버립니다(...)

**Comment by rscarrera27** [comment]
차라리 저녁운동이 괜찮지 않나 싶은데요

**Comment by Lewisxyz000** [comment]
현재 주말을 제외한 나머지 요일에는 아침운동을 합니다. 많은 사람들이 아침운동을 힘들어 합니다... 아침운동을 열심히 참여한다고 해서 돌아오는것도 없고 언제 끝나나 짜증만 날 뿐이고 하루하루 버티기 일쑤입니다. 따라서 한달에 한번 __ 아침운동 없는날__을 건의합니다. 만약 이런 날이 있다면 이런 날을 기다리면서라도 아침운동에 좀더 희망적으로 참여할수 있을 것이라고 생각합니다.
