### ISSUE TITLE
장관님께 드리고 싶은 질문들을 적어주세요.

### ISSUE THREAD

**Issue by SongKJ00** [DSM-HS/student-council#30]
9월 22일 금요일 오후에 진행되는 과학기술정보통신부 유영민 장관님과 함께하는 토크 콘서트에서 질문하고 싶은 내용들을 올려주세요!  장관님만의 경험, 프로그래머로서의 가져야 할 기본 소양 등 자신이 궁금한 점을 자유롭게 표현해주세요~ 
(작성하실 때는 학년 반 번호 이름도 같이 적어주세요~)

**Comment by khg0712** [comment]
우리 학생들이 꼭 해봐야하는 경험, 하면 좋은 것들에는 무엇이 있나요?

**Comment by SongKJ00** [comment]
감사합니다! 감사합니다!! 죄송하지만 학년 반 번호 이름을 적어주시겠어요?

**Comment by KimEJ** [comment]
2-3반 김어진 입니다. 학생신분으로 청중/연사 혹은 staff로 세미나에 참여하는것에 대해서 어떻게 생각하시나요

**Comment by SongKJ00** [comment]
죄송하지만 본 토크 콘서트에서 관련 문제를 언급하는 것은 기피해주셨으면 합니다

**Comment by kyle-seongwoo-jun** [comment]
@khg0712 학번을 적어주시면 좋겠습니다
>감사합니다! 감사합니다!! 죄송하지만 학년 반 번호 이름을 적어주시겠어요?

**Comment by khg0712** [comment]
10302  김형규 입니다

**Comment by Splash3085** [comment]
20102 김경민
대한민국은 현재 성장기를 거쳐 경제 대국으로 거듭났습니다. 이제는 문화 선진국으로 도약해야 할 차례라고 생각하는데, 그러기 위해서 대한민국에서 양질의 콘텐츠를 생산하기 위하여 정부 차원에서의 정책과 학생들이 할 수 있는 노력과 경험이 무엇이 있을지 궁금합니다.

**Comment by kyle-seongwoo-jun** [comment]
@Splash3085 과학기술정보통신부 장관님에게 문화 분야 질문은 별로 합당하지 않는다고 생각합니다만 어떻게 생각하시나요?

**Comment by syeutyu** [comment]
20113 이동현
저희는 앞으로 프로그래머 개발자로 살아갈텐데 능력 좋은 개발자도  중요하지만 
장관님이 생각하시기에 미래의 좋은 개발자는 무엇이라고 생각하시나요? 
그리고 좋은 개발자가 되려면 과연 저희는 무엇을 하는것이 좋다고 생각하시나요

**Comment by usernameSplash** [comment]
@Nuwanda22 맞는 말씀인 것 같네요

**Comment by SeungYongSon** [comment]
10210 손승용
장관님께서는 지금까지 많은 일들을 해오셨을 거고 힘든일, 어려운일, 위험했던일들도 겪어 보았을 겁니다.
그렇다면 장관님께서는 그런일들을 어떻게 해결하고 앞으로 어떻게 나아갔는지 궁금합니다.

**Comment by jychoi415** [comment]
30320 최정연
최근, 책과 뉴스 등 여러 곳에서 '4차 산업혁명' 이 매우 많이 거론되고 있는데, 장관님이 생각하시는 4차 산업혁명이란 무엇인지 궁금합니다.

p.s. 이 질문이 채택된다면, 이에 대한 답변은 개인적으로 후배를 통해 듣겠습니다~^^

**Comment by SongKJ00** [comment]
좋은 질문들 감사합니다. 오프라인으로 작성했던 질문 내용들과 같이 창의적인 질문들을 선별하도록 하겠습니다.
