### ISSUE TITLE
교내 토크콘서트 등을 녹화/자료 배포

### ISSUE THREAD

**Issue by KimEJ** [DSM-HS/student-council#31]
교내 토크콘서트나 구루터 특강, 기타 외부 강사가 오셔서 강연을 하는 것에 대해 보지 못한 학생이나 다시 보고 싶은 학생을 위해 사전 허가 하에 녹화하고 자료를 배포 받았으면 합니다. 어떻게 생각하시나요?

**Comment by usernameSplash** [comment]
@KimEJ 좋은 생각인 것 같습니다. 개인적으로 동의합니다.

**Comment by SongKJ00** [comment]
좋은 안건 감사합니다. 현재 잡혀 있는 업무가 끝난 뒤 최대한 빨리 회의하여 건의해보겠습니다.

**Comment by KimEJ** [comment]
이번 과학기술정보통신부 유영민 장관님이 오시는 토크콘서트도 하는게 좋다고 생각합니다만 불가능할까요?
