### ISSUE TITLE
동아리 시간 교실 온도 불평등

### ISSUE THREAD

**Issue by JoMingyu** [DSM-HS/student-council#32]
예전부터 있었던 일이긴 한데, (세미나실을 제외한)소프트웨어 개발실과 같은 특별실에는 에어컨 제어가 풀려 있고, 세미나실과 교실은 에어컨 제어가 걸려 있는 경우가 많습니다.

오늘(2018-06-08) 7, 8교시에 굉장히 더웠는데, 저희 동아리는 12명의 인원이 좁은 세미나실 2-1에 모여 선풍기 2대로 더위를 버텼습니다. 에어컨이 중앙제어길래 건너편 소프트웨어 개발실에 가봤더니, 그 곳은 에어컨 2대가 틀어지고 있었습니다. 춥다고 가디건을 입고 있더라고요.

더워서 아무것도 할 수가 없습니다. 제발 살려주세요..

**Comment by devsunb** [comment]
학급회의를 통한 새로운 안건 수집 시스템을 이용해 건의해 주시기 바랍니다.
