### ISSUE TITLE
주말 잔류에 관한 사항 / 다과실 자판기 물품 추가 / 기숙사 휴대 전화 사용 완화

### ISSUE THREAD

**Issue by ghost** [DSM-HS/student-council#4]
먼저, 주말잔류자에대한 벌점과 강제화된 자습(오히려 자습을 원치않는 학생들이 분위기를 흐리고 있음), 주말 11시 이후 단전, 휴대폰 수거(노트북은 학교자산이나 휴대폰은 개인자산임), 자유시간 없어짐등은 형편성에 어긋난다고 사려됩니다. 집이 학교로 부터 멀어서 반강제적으로 귀가하는 학생들에게 불공정함이 적용되는 것은 옳지 않습니다. 걱정되는 부분이 위칙행위의 증가일텐데, 위칙 행위는 사감/담임교사의 지도로 해결할 수 있는 부분이라고 사려되기에 꼭 고려해주십시오.

둘째, 다과실 자판기의 품목이 음식류로 한정되는것 같습니다. 필기구, 학용품, 휴지등 의 품목이 추가 되었으면 합니다.

셋째, 휴대폰을 기숙사에서 수거하는 것은 엄연히 '범법행위' 입니다. 국가인권위와 교육부에서는 다양한 국가기관에서 기숙학교에서 휴대폰을 수거하는 것은 "면학분위기 형성은 존중하지만 도를 넘어 지나치면 인권침해" 라던가 "학교 측이 면학 분위기 조성 차원에서 휴대전화 제한이 불가피하다고 주장하나 월요일부터 금요일까지 휴대전화를 전혀 쓰지 못하게 하는 것이 이런 목적을 달성하는 데 적합하고 효과적인 수단은 아닌 것으로 판단된다" 라고 지적하기도 했습니다. 이는 엄연히 잘못된 규정이니 사라져야 합니다. 휴대폰의 수거로 인해 학생들이 위칙행위에 빠지기 쉽고, 친구들과의 소통도 많이 단절된다는 느낌도 큽니다. 심지어 얼마전에는 학교에서 휴대폰 수거를 하지말라고 공문도 내려오고 기사도 나왔죠.

#### 제안 사항
- 주말 잔류에 관한 사항
    - [ ] 자습 강제화
    - [ ] 11시 이후 전기 사용
    - [ ]  휴대전화 사용 자유화
- [ ] 다과실 자판기 품목 추가
    - 필기구 / 학용품
    - 휴지 및 생활용품
- [ ] 기숙사 휴대전화 규제 완화

**Comment by kyle-seongwoo-jun** [comment]
- [ ] 주말 잔류에 관한 사항
    - [ ] 자습 강제화
    - [ ] 11시 이후 전기 사용
    - [ ]  휴대전화 사용 자유화
- [ ] 다과실 자판기 품목 추가
    - [ ] 필기구 / 학용품
    - [ ] 휴지 및 생활용품
- [ ] 기숙사 휴대전화 규제 완화

**Comment by kyle-seongwoo-jun** [comment]
@HupungJ 말씀하신 사항을 정리해봤습니다. 오류사항 없는지 확인 부탁 드립니다.

**Comment by ghost** [comment]
넵 충분한 것 같습니다.

**Comment by jwqe764241** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
