### ISSUE TITLE
점호시간 이후 취침 시간 문제

### ISSUE THREAD

**Issue by 98ff98** [DSM-HS/student-council#5]
저희 학교 기숙사의 취침시간은 원칙적으로 **점호시간 이후 ~ 다음날 오전 6시** 입니다.
이건 2015년에 학교가 처음 개교했을 때 부터 기본적인 원칙이였으며, 지금까지도
많은 선생님들이 관련 지도를 하실 때 언급하시고 계십니다. 

하지만 현재의 상황은 이와 많이 다릅니다.
학생들의 수면권 보장을 위해서 만든 취침 시간의 마지노선인 **11**시가 
마치 **기본 취침 시작 시간**인 것 처럼 운영되고 있으며, 이 시간 전에 취침을 하는
학생들에 대한 배려는 **단 하나**도 없습니다

이로 인해 몸이 아프거나 전날에 해커톤등에 참여해서 너무 피곤해서 일찍 자려고 마음을 먹어도 
결국에는 실패하고 짜증만 잔뜩 난 상태로 **11**시를 넘겨서 잠에 드는 경우가 많습니다.

우선 기숙사가 11시 이전까지 너무나 소란스러운데,
복도에서 소리를 지르고 큰 소리로 떠들고 뛰어다니는 것은 기본입니다.

또한 사감 선생님들의 잘못도 있는데, 11시 이전에 수시로 방송을 해서
복도의 소음을 이겨내고 잠을 청하고 있는 학생들을 깨워버시리며,
실질적으로 기숙사 운영의 주축이시면서 기본 원칙에 어긋난 운영을 하십니다.

**제발 조기 취침자 혐오를 멈춰주세요**

#### 제안 사항
- 11시 이전 취침자 배려
    - [ ] 점호 이후 복도 정숙
    - [ ] 점호 이후 호실 내 방송 자제

**Comment by kyle-seongwoo-jun** [comment]
### 제시 안건
- [ ] 11시 이전 취침자 배려
    - [ ] 점호 이후 복도 정숙
    - [ ] 점호 이후 호실 내 방송 자제

### 제시 근거
* 학교 기숙사의 취침시간은 원칙적으로 _점호시간 이후 ~ 다음날 오전 6시_ 이나 11시가
마치 기본 취침 시작 시간인 것 처럼 운영되고 있음
* 점호 시간 이후로 취침을 하는 학생들에 대한 배려가 없음

**Comment by seunghun-kim** [comment]
복도는 사실 상당히 조용합니다. 오히려 시도때도 없이 나오는 방송이 문제죠. 학생 2명 불러놓고, 10분 후에 또 한 명 부르고... 사감선생님들은 부를 학생들을 버퍼에 넣어두었다가 일정량 이상이 되었을 때 한번에 방송을 해야 한다 봅니다.
