### ISSUE TITLE
급식실 자리 문제

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [DSM-HS/student-council#6]
급식실에서 자리 앉을 때 온 차례로 앉아 같이 온 친구들과 같이 못 앉게 되는 경우가 종종 발생합니다.

이에 대해 학생들의 탁월한 해결책을 **공모**합니다.

다수의 학생들이 동의하는 의견은 급식실 자리 문제를 해결하는 데 **적극 반영**됩니다.

많은 학생 여러분의 참여 부탁드립니다.

#### 제안 사항
- [ ] 학교 급식실 착석 문제 해결

**Comment by Kinter** [comment]
급식 받는 줄이 두줄인데, 현재는 어느 줄에서 급식을 받든 같은 테이블로 앉게 되어 있습니다. 두 줄을 서로 다른 테이블로 앉게 하면  같은 줄에 서서 급식을 받는 친구들끼리 앉을 수 있을 것 같습니다.

**Comment by AshtonYoon** [comment]
![presentation1](https://cloud.githubusercontent.com/assets/16028154/24906813/4e3c32d8-1ef4-11e7-892e-5a7a2e1af237.png)
이렇게...?

**Comment by Kinter** [comment]
@AshtonYoon 네. 그런식으로요. 그림으로 정리해 주셔서 감사합니다.

**Comment by poca-p0ca** [comment]
급식받는 줄에 따라서 테이블 배치를 정하는 것은 무리가 있다고 생각합니다. 급식 받는 줄이 두줄인 점은 순전히 배식 속도를 빠르게 하기위한 것 그 이상 그 이하도 아닙니다. 오히려 그렇게 하면 나중엔 몰라도 이 점을 몰랐던 학생들에게 혼란을 줄 수도 있고, 자리 선점을 위해서 무리하게 학생들이 한쪽 줄만 점유하게 될 가능성도 있습니다.

**Comment by graykick** [comment]
지정석을 정해두고, 한 달혹은 몇 주 단위로 바꾸는 방법도 있습니다. 이 지정석을 정하는 방법에 대해서는 많은 방법들이 있습니다. 
지정석이 좋은 해결책이 될 수 있다면, 자리배정 문제에 대해서는 후에 다함께 고민해야 할것 같습니다

**Comment by rhaeovh** [comment]
우리 학교가 군대도 아니고 대체 왜 한명씩 착착 맞춰서 앉아야 하나요
학생들이 사용하는 테이블을 줄여서 급식 도우미 선생님등 일을 줄이자는 취지로 시작한 건 좋은데, 어차피 이제 1학년들 새로 들어오면서 사용하지 않는 테이블이 없어졌어요. 그런데도 선생님들은 사정 전혀 봐주지 않고 무조건 먼저 온 순서대로 한 명씩 앉으라고 시키시고, 심지어 앉으라는 자리 옆 자리에 앉았다고 사감실에 알려서 벌점을 매기는 거 보고 정말 쓰레기같은 제도라고 생각했어요. 괜히 맞춰 앉힌다고 학생들 괴롭히지 말고 의자 자유롭게 앉을 수 있도록 풀어달라고 전해주세요 🙂

**Comment by jwqe764241** [comment]
그냥 학년별로 구역을 나누어서 앉는게 좋을것 같습니다.

솔직히 님들이 느끼는 가장 큰 문제는 다른 학년이랑 앉기 때문이죠; 가장 현실적인 방법은 학년별로 구역을 나누어서 그 안에서 자유롭게 앉던 하는게 가장이라고 생각합니다. 

많은 분들이 제한을 풀어달라고 하시는데... 아무 제한 없이 자유롭게 앉게되면 자리는 부족하게 되어있습니다.

**Comment by jwqe764241** [comment]
![default](https://cloud.githubusercontent.com/assets/13945127/24911214/2e32944e-1f05-11e7-807f-1357042ac195.png)

사실상 저래 됬었습니다. 물론 저기에 다른 애들이 붙으면 되지만 관찰한 그런 경우도 몇 없었구요. 남북한인줄 알았습니다 ㅋ..

**Comment by rhaeovh** [comment]
어차피 밥은 친구들이랑 먹는데 다른 학년이랑 앉는다고 문제 될 게 있을까요? 또 학년 별로 구역을 나누게 되면 동아리나 프로젝트 등으로 다른 학년과 함께 밥을 먹는 경우 따로 떨어지게 됩니다. 그리고 저런 식으로  가운데 자리가 비더라도 나중에 사람이 많아지면 다시 차게 됩니다. 자유롭게 앉게 되면 자리가 부족하게 된다는 말이 도무지 이해가 되질 않네요

**Comment by poca-p0ca** [comment]
무슨 쌍팔년도 고등학교에서 선후배 사이가 하늘과 땅차이인 것 마냥 사이를 갈라놓는 것 같다고 생각합니다. 타 학년끼리 친한 경우도 얼마든지 있는데 학년 별로 갈라놓는 것은 부적절 하다고 생각합니다.

**Comment by jwqe764241** [comment]
저 의견이 어떻게 쌍판년도 선후배 관계를 나타내는지 궁금합니다. 오히려 쌍팔년도 선후배 상하관계였으면 후배가 기었어야 하는게 아닌가요.

타 학년끼리 친한 경우 많은 경우가 있다는 것은 저도  알아요. 근데 이게 또 제한 없이 자유롭게 앉으면 3월달에 있었던 것 처럼 헬 파티가 열리는 건 똑같을겁니다. 그룹끼리 앉겠다고 새로운 테이블로 앉는 등의 문제로 자리가 부족했었고 어쩔 수 없이 자리 적은 테이블로 가서 낙오되고 따로 떨어져서 밥 먹는 건 똑같았습니다.  제가 거의 매일같이 그랬었죠. 질서가 없었기 때문에 지금처럼 답없이 테트리스 하듯 어거지로 끼워 맞추는 거구요.

뭐 제가 본게 다가 아니면 제가 문제겠죠? 적어도 제가 전체적으로 둘러 보았을 때 저랬었습니다. 다들 보셨을 거라고 생각합니다.

그렇다고 해서 계속 이대로가 제일 좋다? 그것은 아닙니다. 저도 지금 방식 마음에 들지 않습니다. 친한 친구들 끼리 앉고싶은 여러분들 마음 이해합니다. 저도 친한 친구들 끼리 앉고 싶거든요. 근데 또 이런 제한이 없는것도 저는 마음에 들지 않습니다. 위에서 말한것 처럼 될거거든요.

어차피 몇 분 밥 먹고 갈 거 학년별로 앉는다고 해서 막 사이가 멀어지나요? 저는 그렇게 생각하지 않습니다. 고작 급식 하나 같이 안먹었다고 인연 끊긴다면 그것은 진정한 친구라고 생각하지 않습니다. 저는 다 먹고 합류하면 된다고 생각합니다.

내 의견이 최선책이다. 라는 것은 아니고 그냥 제가 생각하기에 저것이 가장 좋다고 생각하는 것입니다. 잘만 되면 문제가 없겠지만, 이상과 현실은 다릅니다. 뭐 그냥 자유롭게 앉고 문제점은 감수하는것도 방법일 수 있습니다.

제가 타인공감능력이 부족하죠 저도 인정합니다. 근데 적어도 의견을 제시하는게 맞다고 봅니다. 여기는 의견을 제시하는 것이지 부정을 하라고 만들어 놓은 이슈가 아니기 때문입니다. 부정은 회의 단계에서 해야 할 것이구요. 개인적으로 원한이 있으시면 와서 말해주세요.

이상입니다.

**Comment by poca-p0ca** [comment]
표현이 공격적 이었던 것에 대해선 죄송스럽게 생각합니다. 하지만, 제가 말하고 싶은건 공식적으로 이루어지지도 않은 개인연구에 대한 결과를 토대로 낸 섣부른 판단과 결론에 문제점이 있다는 말입니다. 학생들 상대로 조사를 한 것도 아니고, 단순히 "내 보기엔 그렇던데?"하는 것으로 그러시면 안됩니다. 분명히 예외상황 혹은 현재 내신 안건에 대해 가장 큰 불이익을 보는 학생 또한 존재할 것이고, 이를 무시해선 안됩니다. 개인적인 원한은 없으니까 오해 하지 말아주셨으면 합니다. 솔직히 말해서 아이디 만으로는 누군지도 몰라요.

**Comment by jwqe764241** [comment]
어딜 봐서 개인연구인지 묻고 싶습니다... 다시한번 읽어주시길 바랍니다.

**Comment by ghost** [comment]
학년별로 구역을 정해 앉는 것 매우 동의합니다. 밥 먹을 때 친구들이랑 분리되어서 3학년들 사이에 껴 혼자 밥을 먹는 어린양들을 보면 매우매우 안타까움.  동아리나 프로젝트 관련된 일로 이야기를 나눠야 하는 상황이면, 차라리 밥을 빠르게 먹고 다시 합류하는게 밥 먹는 도중에 이야기를 나누는 것보다 훨씬 집중할 수 있다고 생각합니다.

**Comment by seunghun-kim** [comment]
배식대 줄 별로 다른 테이블을 쓰게 하는 것이 괜찮은 아이디어 같아 보이는데요, 한쪽 배식대에만 몰리게 되는 문제는 크게 걱정할 건 없다고 봅니다. 어차피 한 반 전체가 다 같이 식사를 한다 해도, 줄이 끊이지 않는 급식실에선 짧은 줄은 저절로 메꾸어지지 않을까요? 만약 한쪽에만 몰리게 되는 문제가 생긴다면 줄을 적당히 나눠 설 수 있도록 선생님들이 지도해주시면 좋을 것 같습니다.

**Comment by wlzla000** [comment]
@jwqe764241

> 어딜 봐서 개인 연구인지 묻고 싶습니다... 다시 한번 읽어 주시길 바랍니다.

에 제가 대신 답하겠습니다.

----------

> 어차피 몇 분 밥 먹고 갈 거 학년별로 앉는다고 해서 막 사이가 멀어지거나 그렇습니까? 아닙니다.

상기한 인용문에 나타난 글에서 개인적인 생각을 일반화하는 것으로 보입니다.

----------

참고로 이 글에는 저 의견에 대한 제 생각이 나타나 있지 않습니다.

**Comment by jwqe764241** [comment]
저분은 

무슨 쌍팔년도 고등학교에서 선후배 사이가 하늘과 땅차이인 것 마냥 사이를 갈라놓는 것 같다고 생각합니다. 타 학년끼리 친한 경우도 얼마든지 있는데 학년 별로 갈라놓는 것은 부적절 하다고 생각합니다.


에서


공식적으로 이루어지지도 않은 개인연구에 대한 결과를 토대로 낸 섣부른 판단과 결론에 문제점이 있다는 말입니다. 학생들 상대로 조사를 한 것도 아니고, 단순히 "내 보기엔 그렇던데?"하는 것으로 그러시면 안됩니다.

라고 말씀하시고 싶으셨다는데 제가 저런 글을 쓸줄 어찌알고 

어차피 몇 분 밥 먹고 갈 거 학년별로 앉는다고 해서 막 사이가 멀어지거나 그렇습니까? 아닙니다.

이 부분에서 개인연구라고 하고싶으셨던건지 알고싳네요. 저분 미래에서 왔나요 ㅡ.ㅡ 누가 

왜 그러시죠. 누가 시켰나요. 아니면 제가 틀렸나요. 
저걸로 된다고 하던가요. 그냥 의견을 말했을 뿐인데 왜 그러시는지 모르겠네요. 저분이랑 오해 풀고 다 끝냈는데 지금와서 이러시는 이유 좀 알 수 있을까요; 

참고로 이 글에는 저 의견에 대한 제 생각이 나타나 있지 않습니다.

이런 내용은 왜 넣으셨는지 모르겠네요. 문제가 될까봐 넣으셨나요

저에게 무슨 문제나 잘못된 점, 개인적으로 하고싶으신 말 있으시면 3학년 1반 후문 바로 앞자리에 와서 말해주세요.

**Comment by jwqe764241** [comment]
여기에 코멘트 작성하지 마세요. 직접 와서 말씀주세요

**Comment by jwqe764241** [comment]
아니면 309호 편하실 때 오셔서 말하셔도 됩니다.

**Comment by wlzla000** [comment]
@jwqe764241

 제 댓글에 왜 그렇게 반응하시는지 모르겠습니다. 조금 당황스럽네요. 적어도 저는 아무 감정 없이 쓴 글이었다는 점을 알아 주시면 좋겠습니다.

> 왜 그러시죠. 누가 시켰나요. 아니면 제가 틀렸나요.

> 저걸로 된다고 하던가요. 그냥 의견을 말했을 뿐인데 왜 그러시는지 모르겠네요. 저분이랑 오해 풀고 다 끝냈는데 지금와서 이러시는 이유 좀 알 수 있을까요;

라고 **물으셨으니** 답하겠습니다. 인용문이 많이 필요할 듯하니 구술로 답하는 건 힘들 것 같습니다.

----------

## 그 댓글을 단 이유

이 이슈 스레드에서, @Cyanide7523과 @jwqe764241 간의 대화 중 가장 마지막 댓글은

> 어딜 봐서 개인 연구인지 묻고 싶습니다... 다시 한번 읽어 주시길 바랍니다.

이라는 말이었습니다. 그 **`묻고 싶습니다.`**라는 말이 _자신의 댓글 내용 중에서 개인적인 의견을 일반화한 부분이 있는지 알고 싶다_는 말이 아니었나요? 저는 그렇게 해석하였습니다. 이게 제가 댓글을 단 이유입니다.

그 다음에 @Cyanide7523의 댓글이 없길래, _제가_ 상기된 댓글 중에서 개인적인 의견을 일반화하였다고 _판단되는_ 부분을 찾아 알려 드린 것 뿐입니다.

## 왜 그 부분을 `일반화하였다`고 표현하였나?

제가

>> 어차피 몇 분 밥 먹고 갈 거 학년별로 앉는다고 해서 막 사이가 멀어지거나 그렇습니까? 아닙니다.
>
> 상기한 인용문에 나타난 글에서 개인적인 생각을 일반화하는 것으로 보입니다.

라고 말했죠. 저 말에서, 그렇게 생각하지 않는 사람도 있을 수 있다는 점을 고려하지 않으신 듯하여(`그렇습니까? 아닙니다.`) `개인적인 생각을 일반화하였다`고 표현한 겁니다.

## `참고로 이 글에는 저 의견에 대한 제 생각이 나타나 있지 않습니다.`

>> 참고로 이 글에는 저 의견에 대한 제 생각이 나타나 있지 않습니다.
>
> 이런 내용은 왜 넣으셨는지 모르겠네요. 문제가 될까봐 넣으셨나요

라고 물으셨으니 이것도 답하겠습니다.
우선 분명히 말해 두건대, 저는 항변하는 글을 쓴 적이 없습니다.
그러니 저 글을 넣든 빼든 문제가 될 건 없습니다.

저 글의 의미는 **말 그대로** 상기된 제 댓글에 당신의 의견에 대한 제 생각이 담겨 있지 않다는 뜻이었습니다.

또, 저 글을 글 끝에 덧붙인 이유는 당신이 제 댓글을 당신의 댓글에 항변하는 내용으로 인식할까 봐 넣은 것입니다. 지금처럼 말입니다.

> 저는 여러분의 토론에 아무런 의견도 표현하고 있지 않습니다.

라고 말한 셈이죠.

**Comment by jwqe764241** [comment]
이해를 못하셨나 본데 제가 묻고싶은건 왜 개인연구가 어디있는지에 대한 답을


>저 의견이 어떻게 쌍판년도 선후배 관계를 나타내는지 궁금합니다. 오히려 쌍팔년도 선후배 상하관계였으면 후배가 기었어야죠.

>타 학년끼리 친한 경우 많은 경우, 저도 다~ 알아요. 근데 이게 또 제한 없이 자유롭게 앉으면 3월달에 있었던 것 처럼 헬 파티가 열리는 건 똑같을겁니다. 자기들 무리끼리 앉겠다고 새로운 테이블로 앉는 등의 문제로 자리가 부족했었고 어쩔 수 없이 자리 적은 테이블로 가서 낙오되고 따로 떨어져서 밥 먹는 건 똑같았습니다. 제가 거의 매일같이 그랬었죠. 질서가 없었기 때문에 지금처럼 답없이 테트리스 하듯 어거지로 끼워 맞추는 거구요.

>뭐 제가 본게 다가 아니면 제가 문제겠죠 ㅋ.. 적어도 제가 전체적으로 둘러 보았을 때 저랬었습니다.

>그렇다고 해서 계속 이대로가 제일 좋다? 그것은 아닙니다. 저도 지금 방식 마음에 들지 않습니다. 친한 친구들 끼리 앉고싶은 님들 마음 이해합니다. 저도 친한 친구들 끼리 앉고 싶거든요. 근데 또 이런 제한이 없는것도 저는 마음에 들지 않습니다. 위에서 말한것 처럼 될거거든요.

>어차피 몇 분 밥 먹고 갈 거 학년별로 앉는다고 해서 막 사이가 멀어지거나 그렇습니까? 아닙니다. 다 먹고 합류하면 그만입니다. 같이 안 먹었다고 걔네들이 뭐라고 합나요. 그것이 더 이상한 것입니다.

>내 의견이 최선책이다. 라는 것은 아니고 그냥 제가 생각하기에 저것이 가장 좋다는 것입니다. 잘만 되면 문제가 없겠지만, 이상과 현실은 다르니까요. 뭐 그냥 자유롭게 앉고 문제점은 감수하는것도 방법일 수 있습니다.

>제 말이 아니꼬아서 그냥 부정만 하시는것은 다~~ 이해합니다. 제 의견이 된다는 보장도 없는데 말씀하시는 것들은 제 의견이 된것 처럼 말씀들 하시네요. 제가 타인공감능력이 부족하죠 저도 인정합니다. 근데 적어도 의견을 제시하는게 맞다고 봅니다. 여기는 의견을 제시하는 것이지 부정을 하라고 만들어 놓은 이슈가 아니기 때문입니다. 부정은 회의 단계에서 해야 할 것이구요. 개인적으로 원한이 있으시면 와서 말해주세요.

>이상입니다.

이 부분에서 찾으셨냐고 묻는겁니다.

그리고 위에 말씀드렸듯이 오셔서 말씀해주세요.

**Comment by jwqe764241** [comment]
>그 다음에 @Cyanide7523의 댓글이 없길래

왜 댓글이 없을까요? 위에 말씀드렸듯이 오해 풀렸고 해결됬습니다.

**Comment by jwqe764241** [comment]
>또, 저 글을 글 끝에 덧붙인 이유는 당신이 제 댓글을 당신의 댓글에 항변하는 내용으로 인식할까 봐 넣은 것입니다. 지금처럼 말입니다.

마치 이 부분을 추가 하지 않았으면 제가 뭐라 하겠다라고 생각하신것 같은데 정 반대입니다 -.-

자신의 관점에서 생각하지 마시고 타인의 관점에서 생각하시길 바랍니다. 타인을 모르면서 그렇게 하시면 안되죠 ㅋ.

**Comment by jwqe764241** [comment]
이 이상 뭐라고 하진 않겠습니다만 전 3학년 1반 김기준입니다. 1반 후문 바로 앞쪽 자리에 앉고 있고 기숙사 호실은 309호 입니다. 하실 이야기는 여기에 달지 마시고 오셔서 말씀해 주세요.

**Comment by jwqe764241** [comment]
여기는 말 그대로 의견을 공모하는 것이지 의견에 대해서 반박하라고는 하지 않았습니다. 반박은 회의 때 할 것 아닌가 생각해봅니다. 

그래서 계속 와서 말씀해 달라고 하는 겁니다만 계속 여기에 코멘트를 다는 이유를 모르겠습니다.

**Comment by wlzla000** [comment]
@jwqe764241


1. 제가 글을 잘못 읽었다는 점을 방금 파악했습니다. 무슨 말씀인지 이제야 알겠네요. '개인 연구'가 있다고 표현한 글이 11일 전의 글이 아니라 12일 전의 글이었군요. 제 오해로 불필요한 대화가 발생한 점에 대하여 죄송하다고 하고 싶습니다. 하지만 그와는 별개로 제 의견은 여전히 유효하다고 생각합니다.

2. '오해 풀렸고 해결됨'을 이 스레드 읽는 저로서는 알 수 없다는 점을 고려해 주시면 좋겠습니다.

3. 그 글을 읽을 모든 이의 생각이 무엇이든 상관없이, 그 글은 제 글을 더 정확하게 이해할 수 있도록 하기 위한 장치이자, 사실일 뿐입니다.

4. 의견에 반박(항변)한 적은 없습니다. 이 부분은 말씀드렸습니다.
