### ISSUE TITLE
기숙사 벌점 문제

### ISSUE THREAD

**Issue by u-dair** [DSM-HS/student-council#7]
기존에는 매달마다 상점을 차감하여 벌점을 차감할 수 있어 기존 튼튼교육이나 봉사활동을 하는 것을 무마할 수 있었는데, 이제는 봉사활동을 하는 것으로만 벌점을, 그것도 제한이 있게 차감할 수 있게 되었기 때문에 사실상 벌점 차감의 의미가 없어진 게 아닌가하고 생각이 듭니다. 이제 상점을 받는 것도 별다른 감흥이 없고, 그냥 벌점을 받게 되면 욕부터 나옵니다.

또, 주변에 몸이 아파서 일찍 일어나 다른 애들보다 일찍 일어나 준비할 수도 없고, 휘청대면서 걸었던 애들도 있는데 그런 애들한테는 다른 기준을 적용해야 하지 않을까요? 몸이 아파서 빨리 갈 수는 없는데 아침 점호나 등교 시간에 늦었다고 벌점까지 받으니 억울하다고 합니다.

#### 제안 사항
- [ ] 기존처럼, 매 달 상점 결산일에 이미 있는 상점을 소모하는 것으로 벌점을 차감할 수 있게 하자.
- [ ] 아파서 모이는 것이 늦은 애들을 위한 별도의 기준을 마련하자.

#### 추가 의견
- [ ] 벌점 유지기간을 1학기로 축소
- [ ] 귀사 지각 벌점 완화

**Comment by rscarrera27** [comment]
현행 제도를 유지하는것도 괜찮지만 만약 그 경우에는 1년은 너무나 무리라고 생각합니다.
**1학기 정도**로 벌점 유지기간을 줄이는것이 합당하다고 생각합니다.

**Comment by 98ff98** [comment]
귀사 지각 벌점이 말도 안되게 높습니다...
단 1분만 지각해도 벌점 3점이라는 것은 납득하기 힘듭니다.
30분이상 지각시 3점, 그 미만은 1점으로 하는 것이 타당하다고 생각합니다
