### ISSUE TITLE
GitHub 학생회 홍보 강화

### ISSUE THREAD

**Issue by jaemin-im** [DSM-HS/student-council#8]
저는 1학년 학생 임재민이라고 합니다. 이번에 페이스북에서 GitHub 학생회를 보고 이렇게 찾아오게 되었습니다.
페이스북에서 학생회장 선배님이 홍보를 하셨음에도 불구하고, 아직 대부분의 학생들이 존재 자체도 모르고 있습니다. 이에 괜찮은 홍보 방법을 찾아보는 것이 좋겠다고 생각하기에 이슈를 올려봅니다.
또, 아직 학생회 그룹원이 아닌 경우는 라벨 선택이 안되므로, 이 역시 수정해주셨으면 좋겠습니다.

#### 제안 사항
- [x] GitHub 학생회의 활발한 활동을 위해 홍보 방법을 찾자.
- [x] ~~비그룹원이 라벨을 붙일 수 있게 하자~~ _(그룹 가입으로 해결)_

**Comment by kyle-seongwoo-jun** [comment]
@Xsolute 학생회 홍보가 부족한 점은 저도 동의합니다. 추후에 모든 학생들이 알 수 있도록 전체적으로 공지할 생각입니다. 말씀하신 라벨의 경우, 대덕소프트웨어마이스터고등학교 학생이시면 현 그룹에 초대해드리고 있으며 학교 구성원이 아닌 비그룹원의 라벨 선택은 허용할 예정은 없습니다.

**Comment by kyle-seongwoo-jun** [comment]
#9 에 그룹 가입 신청 안내 방법을 게시했으니 참고해주시길 바랍니다.

**Comment by rscarrera27** [comment]
1학년 김성현입니다. 아무래도 단시간에는 온라인 상으로 한계가 있다고 생각합니다. 오프라인으로 공지가 필요하다고 생각합니다.

**Comment by kyle-seongwoo-jun** [comment]
@Xsolute @Lewisxyz000 
* 4월 17일 아침시간 전학생 조회 시간 공지
* 급식실 올라가는 계단 안내 포스터 공지

위 내용으로 해당 안건은 시행되었습니다. 많은 관심 감사드리며 여러분들이 친구분들께 전달해주시면 더욱 홍보가 될 수 있을 것 같습니다. 감사합니다 😄
